### ISSUE TITLE
Shelves don't render properly from back

### ISSUE THREAD

**Issue by shadowfacts** [Nuchaz/BiblioCraft#218]
When looking at shelves from the back, items/blocks in them don't render.

From the back:
![2014-11-26_21 14 39](https://cloud.githubusercontent.com/assets/7091588/5211480/6face096-75b1-11e4-8747-fa2db73dfcc0.png)

From the front:
![2014-11-26_21 14 44](https://cloud.githubusercontent.com/assets/7091588/5211482/77d489c2-75b1-11e4-80f8-2fbdccd08237.png)

**Comment by Nuchaz** [comment]
Fixed in BiblioCraft 1.9.2
