### ISSUE TITLE
Armor Stand Dupe Bug

### ISSUE THREAD

**Issue by SirWilli** [Nuchaz/BiblioCraft#220]
hey,

unfortunately it is possible to push the top block of the armor stand with a piston. If you place a crafting station from TiCon or arcane worktable from thaumcraft next to the armor stand with a crafting recipe in it and you push the top block of the armor stand it will create a ghost block above the table. If you break the ghost block it will break the bottom block and drops the items + the crafting result.

**Comment by SirWilli** [comment]
Fixed?

**Comment by Nuchaz** [comment]
Yeah, I put a fix in for this in the BiblioCraft 1.9.2 release.

**Comment by SirWilli** [comment]
Okay thanks.
