### ISSUE TITLE
Bibliocraft for minecraft 1.8

### ISSUE THREAD

**Issue by McBossKiller** [Nuchaz/BiblioCraft#223]
forge has updated to minecraft 1.8 and i was hoping this mod would update to the new minecraft 1.8 forge.

**Comment by rustyshakelford2** [comment]
Any news on a 1.8 version?

**Comment by Nuchaz** [comment]
No news yet. I am currently still waiting for forge to add a few things. I have an got the conversation going about what I need over in one of the issues on forges github. Long story short, 1.8 broke rendering so bad in minecraft that even after all this time forge still hasn't gotten caught up to having the capabilities that I am using in 1.7.10. I am definitely still planning to update, I'm just playing the waiting game.

**Comment by bluespace99** [comment]
Please doing your best.
We're rooting for you from Tokyo, Japan.
