### ISSUE TITLE
Request: OreDict entries and recipes for Bibliocraft Lamps

### ISSUE THREAD

**Issue by MalkContent** [Nuchaz/BiblioCraft#226]
When using NEI to look for recipes with dyes or bibliocraft lamps, the recipes are veritably spammed with every possible previous lamp that get's recolored. If you'd use oredict entries for the lamps and adjust the recipes accordingly, we'd be left with one entry per lamp :)

PS: also goes for the sword pedestal

**Comment by Nuchaz** [comment]
Thats a good idea. I didn't know the ore dictionary could be used like that to kind of manipulate the NEI results. I like that. Thanks for the tip, I'll spend some time and check that out when I get some time. I'm not sure at this point if I will do another update for 1.7.10, but I'll try to work this in if I do. I've started work on the update to 1.8, so I'll see how that goes first.

**Comment by MalkContent** [comment]
:)
also now that I read "sword pedestals" again: I'd love to be able to access the inventory of sword pedestals so they could get filled automatically. I tried to force insert a Thaumcraft staff into one, once and was a little sad that golems and hopper(ducts) couldn't access them at all :c

**Comment by MalkContent** [comment]
Shiiiiit. I may have given you bad advice. You only have one Item/ItemID per LanternType so using an OreDict entry would be over the top. You can just use OreDictionary.WILDCARD_VALUE for the ItemStacks damage value in recipes to make the recipe only care about the Item and not the damage value.  
Apologies and please ack this when you read it, cause otherwise I'll spam any address I find of you with it \^\^ I don't want to have talked you into shit code ;_;
