### ISSUE TITLE
Crash with BiblioCraft [tables] when switching servers on a BungeeCord/Cauldron server

### ISSUE THREAD

**Issue by Nentify** [Nuchaz/BiblioCraft#227]
Hello,

I'm currently experiencing quite a major issue with your mod and interactions with Bungee/Cauldron. When switching servers (server A -> server B) with a table in the user's view on server A (only block it has been tested with so far), the user will crash to the desktop with one of the crash reports shown below. I believe this is caused during the handshake reset when moving servers, and your mod doesn't handle ID mapping changes very well.

Crash reports:
http://hastebin.com/ufipugarab.coffee
http://hastebin.com/asocubelod.coffee

A change was made here for BungeeCord: https://github.com/MinecraftForge/FML/commit/292be72639feded03ced26d9a06a98159f7a95b7 and apparently there is an event to help with this issue.

If you want to reproduce it yourself, I can try to setup a 100% success rate crash server setup for you.

If you need any more information, I'm available on IRC (Nentify, in #tekkify amongst other channels), as well as GitHub I guess. I'd be happy to help out where I can.

**Comment by Nuchaz** [comment]
Yeah, I've seen this issue come up a couple times in the past, usually with one of these mcpc, cauldron or whatever servers. As far as I know, mapping changes are handled by forge and there really isn't anything I can do about it. So yeah, I just don't know of anything I can do about that bug. I don't really have any experience with non pure-forge servers, so I can't really comment on the specifics of cauldron or bungeecord (first I've heard of that one).

**Comment by Nentify** [comment]
Ok thanks anyway. BungeeCord is software that allows you to 'link' multiple servers together, at so you can switch servers without having to disconnect. I'll have to continue investigating and see if anything can be done with Forge/Bungee. Thanks again.

**Comment by Nuchaz** [comment]
Thanks for the info on BungeeCord, that kind of gives me a better picture of what is happening for you. If you do come across something that indicates something that I can do on my end to help fix the problem, let me know and I'll investigate it further.

**Comment by Nentify** [comment]
No worries, and yeah, I think some data is getting left behind or something, or mods aren't quite handling the handshake reset as well. More troubleshooting required!
