### ISSUE TITLE
Weird Tool Rack Rotation

### ISSUE THREAD

**Issue by Parker8283** [Nuchaz/BiblioCraft#228]
When I place a tool rack, it always rotates WEST after a moment and stops displaying the items. When I click on a place, it will reset, show everything, and drop/take the tool, then after a moment, reset to rotate WEST. Running 1.9.2 with Forge 1284.

**Comment by Nuchaz** [comment]
That is a really odd bug, I hadn't seen / heard of that one before. What version of BiblioCraft are you using?

**Comment by Parker8283** [comment]
"Running 1.9.2 with Forge 1284."

**Comment by Nuchaz** [comment]
Doh, I must be blind. For some reason I read that as 1.7.2 and was thinking that was your version of minecraft. I can't reproduce this on my end so I guess I am going to need a little more info.
Is this SSP or on a server? What other mods are you running?

**Comment by Parker8283** [comment]
It's all good, and if anyone is still running 1.7.2, I'd be surprised :P

SSP. I notified you as I didn't experience this bug prior to updating Bibliocraft from 1.9.1 and 1.9.2. Also in this update wave, I updated forge to 1284 from I don't remember :P, updated Thaumcraft to 4.2.3.0, added Thaumic Energistics and the Thaumcraft NEI Plugin. Prior to doing this, I didn't experience this bug.

**Comment by Parker8283** [comment]
I'll get you a full mod list later if you need it.

**Comment by Parker8283** [comment]
http://pastebin.com/hp2pZnnN

**Comment by Parker8283** [comment]
Found the bug. It was with Forge 1284. Updating to Forge 1286 fixed it. Some bug in the Tile Entity refreshing code in the chunk.
