### ISSUE TITLE
Typesetting table crash

### ISSUE THREAD

**Issue by Nentify** [Nuchaz/BiblioCraft#229]
When a user opens a typesetting table, they get this crash: http://pastebin.com/X1XsD7XY

I don't crash when opening it, and the last thing they supposedly did was attempt to save a big writing book. The book list was empty when accessing it.

**Comment by Nuchaz** [comment]
It looks almost like maybe the book saved on their local client and not the server and it thinks there is a book there for that player, but the server doesn't have it so it crashes. It shouldn't do that. It may be possible I have a derp in my code dealing with the big books on servers. I'll investigate this further when I get some time.
