### ISSUE TITLE
crash with oak map frame and hopper

### ISSUE THREAD

**Issue by jac2084** [Nuchaz/BiblioCraft#230]
found a nasty little crash reproduced by placing oak map frame on a wall then placing generated map inside the frame and then placing vanilla hopper under the map frame.
crash log: http://pastebin.com/4R878kjx

**Comment by Nuchaz** [comment]
I was able to reproduce this. I'll get a fix in for this in the next release for sure. I am planning another 1.7.10 release.

**Comment by Nuchaz** [comment]
I have the fix in place in code and it will be included in the next release.
