### ISSUE TITLE
[Suggestion] Blibliowoods for Witchery & Dendrology/Ancient Trees

### ISSUE THREAD

**Issue by InkDragon** [Nuchaz/BiblioCraft#231]
Would love to see support for both of these mods.

Witchery can be found here
http://minecraft.curseforge.com/mc-mods/69673-witchery

Dendrology/Ancient Trees is here
https://github.com/MinecraftModArchive/Dendrology

**Comment by JAWSAWN** [comment]
Whops didn't see your post, I made a similar post but it includes Thaumcraft,Withery and TwilightForrest. Also why not the Botania?
https://github.com/Nuchaz/BiblioCraft/issues/236

**Comment by InkDragon** [comment]
I dont have any experience with botania so I can't really comment on it. I believe Twilight forest woods actually just use the vanilla planks, and I'm not sure thaumcraft has plank versions of their wood.

I know both the mods I mentioned actually do have plank versions of their wood just as mods like natura and forestry do.

On an offhand note @Nuchaz may wanna talk to @InfinityRaider who made Agricraft to see how he got his mod to accept and generate a wood type specific items for every plank type installed, as I've yet to find incompatible planks. Which means in theory bilbiowoods would no longer need to be a separate add-on and could just be part of the default mod.

**Comment by JAWSAWN** [comment]
Yes I'm not sure about the Twilight Forrest. It might be using regular wood.
But:
Thaumcraft:
Greatwood Planks
Silverwood Planks

Botania:
Livingwood Planks
Dreamwood Planks

(ps. greatwood is really known in builds)

**Comment by InkDragon** [comment]
just checked twilight forest, only ones I see are tower wood planks, which look very similar in color to jungle wood

Other extra dimensional mods such as Atum, The Elysium and The Erebus add 1, 2, and 13 plank variations respectively, with the last one having quite a bit of crossover with forestry for wood types.

Also I completely forgot about the greatwood planks in Thaumcraft, thanks for pointing them out

**Comment by Nuchaz** [comment]
I am considering thaumcraft, witchery, botania and terrafirmacraft. Enhanced biomes is may be considered too after I check it out a bit. I'm not familiar at all with Ancient trees, but I'll check it out. Thaumcraft only just got slabs a couple weeks ago, which are important for BiblioWoods to make recipes. That is one of the main reasons I am considering doing a small batch of a couple mods since I use thaumcraft and botania in my main survival world. 

I'll have to check out agricraft, but I suspect he may be getting the IIcon from the different wood plank itemstacks kind of like carpenters blocks does and I just haven't figured out a way I can take an IIcon and apply is like a full texture like I would need to in my TileEntitySpecialRenderer(s). Not to mention making recipes, which I've had to do slightly differently for every mod. So yeah, there is some technical reasons why I haven't been able to make the application of different woods from other mods any easier.

**Comment by JAWSAWN** [comment]
Maybe make bibliowoods more open so people can make their own with no coding knowledge?

**Comment by Nuchaz** [comment]
There just isn't any easier way to go about it that I've come up with. Some ideas seem good on the surface, but have technical issues I haven't been able to work around. An alternative would be to have an API, and I am interested in doing that sometime, but I have literally no experience creating an API so I expect a bit of a challenge when I have a go at it so I've been kind of holding off until I know I got a good stretch of time to concentrate on it. Even with an API, you would have to have coding knowledge.

**Comment by InfinityRaider** [comment]
So I got summoned here, I indeed do pull icons from stacks, but I also have a method of getting ResourceLocations from IIcons (this only works for textures that are shipped in the mod's jar though):
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/utility/RenderHelper.java#L39-L44

As far as slabs go, I have not bothered with those yet, but I guess they should be doable.

**Comment by Nuchaz** [comment]
Very nice, thank you InfinityRaider. That looks like exactly what I needed to solve my getting the texture from the IIcon problem. I'll have a play around with that later. That gets me much closer to a more universal solution. 

To get by the recipe issue, It would probably be easier just to have another block, like the facade painter in EnderIO that can just save the string to the resource location to nbt. That would actually negate any need for slabs or anything with that method. 

Anyway, thanks, I'll put some more thought into all this and consider what else I need to do to make a universal solution vs a couple more addons.

**Comment by InfinityRaider** [comment]
It still is a silly workaround, but hey, it works. Only if mods put their textures somewhere else than conventional it will not work :s

**Comment by Nuchaz** [comment]
Here is the first sneak peek on my implementation of this. 
https://twitter.com/Mozzerello/status/571836802270674944

It seems to work real good. I save the IIcon texture name string to NBT and cache the ResourceLocation on NBT load. I tested with a few mods, including forestry, botania and extra trees and I am able to successfully pull and use textures no problems using that method. The only real odd behavior I noticed was the colored wools and stained clays returned IIcon's of the colors in the opposite order. White returned black, orange returned red, etc so I just check the returned string of the icon texture name and change the color to the correct one, a little annoying, but it works. 

Anyway, thanks again, I'm on track to have most of my blocks supported with this method for my next release.

**Comment by InkDragon** [comment]
Awesome! thank you for adding this

**Comment by JAWSAWN** [comment]
Oh my god. I was going to suggest make the bibliocraft carpenters block/typed but then I didn't because that might anger you. Wow thats so awesome

**Comment by InfinityRaider** [comment]
So is this the demise of the BiblioWoods jar files?

**Comment by Nuchaz** [comment]
This is sorta the demise of BiblioWoods, yeah. Though they will still remain fully compatible, I just won't be updating them anymore. Though I am still considering a TerraFirmaCraft BIblioWoods. I feel that needs a lot of extra care to deal with recipes and making that all fit so I think it would still be worth making a BiblioWoods for TFC.

**Comment by InkDragon** [comment]
I totally agree, the way that TFC changed things would makes things so much different would definitely require it's own special consideration
