### ISSUE TITLE
Suggestion: Clipboard peg

### ISSUE THREAD

**Issue by Cobra1117** [Nuchaz/BiblioCraft#232]
Really simple suggestion: A peg that lets you hang the clipboard on a wall.

**Comment by Nuchaz** [comment]
There has been some interest in the past for something like this too. It totally could be done. I'm not sure how readable / large the text can be to fit the entire clipboard into one black space though, that is something I would have to experiment with. Maybe I can make some way to shift-click the clipboard onto / off from a wall or something. I'll look into it more sometime and consider it for a future update.

**Comment by Cobra1117** [comment]
Heh. I wasn't even thinking about making it readable while hanging on the peg (although that would be awesome). Just being able to store it and access it would be great. it could function similar to a reading desk, although it would only hold clipboards. So the controls could be something like:
- Right click to place on peg
- Right click on placed clipboard to access it
- Shift + Right click to remove

Thanks for looking into it :-)

**Comment by Nuchaz** [comment]
https://twitter.com/Mozzerello/status/569991511070408705
;)

**Comment by Cobra1117** [comment]
Sweet! That's even better than I was envisioning. Looking forward to it!
