### ISSUE TITLE
Add enchant and durability check to dinner plates

### ISSUE THREAD

**Issue by Ghostlyr** [Nuchaz/BiblioCraft#233]
Howdy.
Dinner plates have a bug with duplicating enchanted or have a sub-id food. 

Step 1:
Place enchanted item (or with subID) in 3 slots of plate interface.
![screenshot](https://cloud.githubusercontent.com/assets/8511068/5842003/cc6f246c-a1ba-11e4-8216-2d866f7b4554.png)

Step 2:
Put with rightclick items without enchant (or other subID)
![screenshot2228](https://cloud.githubusercontent.com/assets/8511068/5842029/051e6c3c-a1bb-11e4-89da-de94b5e69ecf.png)

Step 3:
Open plate and be in shock.
![screenshot2220](https://cloud.githubusercontent.com/assets/8511068/5842123/ccc0949a-a1bb-11e4-9b88-a312eaa79035.png)

Checked on last version v1.9.2 for MC 1.7.10.
Fix it please.

**Comment by Nuchaz** [comment]
Ok yeah, that looks like an issue that I definitely need to address. I'll see what I can do for the next 1.7.10 update.

**Comment by Nuchaz** [comment]
I got a fix in code for this and it will be included with the next release.
