### ISSUE TITLE
Curseforge

### ISSUE THREAD

**Issue by Claycorp** [Nuchaz/BiblioCraft#235]
With the new curse launcher and other options being added in addition to this will you be adding bibliocraft and the addons to Curseforge?

**Comment by Nuchaz** [comment]
With the curse launcher and such, I am considering getting a curseforge page setup. There already seems to be a bit of interest in the new launcher. I will likely look into it more after I finish another 1.7.10 update.

**Comment by Claycorp** [comment]
I see you uploaded to curseforge! Yay!
Just wanted to point out that you should post each add-on separately and then add them as related projects. You can also include the add-ons original mod in the related projects too.

**Comment by Nuchaz** [comment]
Indeed. :)
Good point on the add-ons, thanks. I am still trying to figure out the best way to organize it. I only got up the bare bones stuff for now and plan to continue adding info and organizing. I'll post an official announcement on my website when I get it all setup. I plan to continue working on it off and on throughout the week as I take breaks from programming and other things.
