### ISSUE TITLE
Reading Enchantment and AE2

### ISSUE THREAD

**Issue by ZeekDaGeek** [Nuchaz/BiblioCraft#239]
SUGGESTION / FEATURE REQUEST

I personally really like the way that the reading enchantment looks in the world, very slick.

It would be nice if I was able to use the reading enchantment to read the names of hard drives in AE2 drives only if they're renamed, that way at a glance I would be able to see which formated hard drives are in a ME Drive or ME Chest.

Another alternative that I've been thinking about is an invisible sign that you could put overtop of a chest or ME Drive that when looked at with a shows the elegant small text that's similar to the reading enchantment. Something that you could right click through to still be able to access the inventory but would allow you to label them. Seeing as they would not be interactable otherwise you would probably need a tool to see them and edit them.

**Comment by Nuchaz** [comment]
That does sound like something that would be nice to have, but I'm afraid it's not really something I can do. The text rendering for my stuff happens in the TileEntitySpecialRenderer, which isn't something I have access to in AE2. There are other ways, like an invisible sign like you mentioned,  but I still don't know that I could easily access the information we would want. That is a bit too specific though, that would have to be more of a AE2 add on rather than something I can really add to default BiblioCraft.

**Comment by ZeekDaGeek** [comment]
The sign idea is independant of AE2, it would be nice to have an invisible sign that can only be read with reading glasses for organizational reasons. The ability to put them on chests without having a sign that prevents right clicking on a large chunk of the block, or put them on ME Chests to allow labeling what was inside of them. It doesn't have to interact with the information automatically.

**Comment by Nuchaz** [comment]
Ah, I see what you mean, something you can add info manually. That is a pretty interesting idea. It would still have to have some small patch in the way so you could click to open the interface and I likely couldn't have separate "regions" you could look at to show different text. Though, it might not work anyway. I found when rendering text, I had no control over the rendering order of the different TESR's, so other things will render over the top of the text unless I render something solid behind behind the text in the same TESR the text is being rendered in. It has something to do with the way text is rendered. So there is a good chance an invisible sign wouldn't work in the same way the other stuff does. I would likely have to make the text pop up on your screen like you see the tape measure text measurement. I'll investigate it further when I get time, but I don't it will work like we want.
