### ISSUE TITLE
Painting Frames causing painting to look different sizes

### ISSUE THREAD

**Issue by SethCarmikle** [Nuchaz/BiblioCraft#242]
Whenever I set a painting canvas on the painting frame, I can set it up to look like it fits my wall in my house on my server. Whenever anyone else looks at it though, it extends way beyond my wall and outside of my house. I am the only one who sees it as just the size of my wall.

**Comment by Nuchaz** [comment]
hmm, sounds like some sort of sync problem. I'll do some tests and try to replicate it and see if I can find a fix.

**Comment by Nuchaz** [comment]
I've tried to reproduce this,  but I've had no luck. Are you using any type of modified server (like Bukkit, or Spout, or MCPC, or whatever is out there now)? I've had problems with some of those extended server versions messing with packets before, and there isn't anything I can really do about that. I can basically only be sure it works with standard forge. If that isn't that, I'm not sure what is going on.

**Comment by SethCarmikle** [comment]
No, I am using a standard version of forge. I am actually using the Direwolf20 1.7.10 mod pack. In game the settings show a painting size of 2x2 and shows up correctly on my end, but everybody else sees it larger than that. The only time they see it the same size as me is if I set it the scale to 1 and the aspect ratio to 1:1. Anything else and they see it as a larger image than mine.

**Comment by Nuchaz** [comment]
Hmmm, interesting. I'll do some more investigating with the DW20 pack like you have and try to reproduce the issue with that when I get some time.
