### ISSUE TITLE
v1.9.2 Nothing rendering...

### ISSUE THREAD

**Issue by Beelzaboss** [Nuchaz/BiblioCraft#243]
Hi there,

I have this weird thing going on with BiblioCraft, It work fine on a old old 1.7.10 version (Could not remember exact version). But since I updated the mod it's only showing frames now, I tried every block... - They only have a selection frame over it if I hover with my mouse over it. I went back to version v1.9.1 and it still does not render anything...

I un-installed Optifine and also reset'd graphic settings to default, No luck.

Any assistance will be greatly appreciated :smile:

**Comment by Nuchaz** [comment]
The first thing that comes to mind is there is a config option in the BiblioCraft.cfg that can disable rendering. Perhaps that has been changed. You can either go through the cfg and try changing it, or just delete the cfg and let it regenerate.

**Comment by Beelzaboss** [comment]
Omw... How did it change to true :P.

Thanks :D
