### ISSUE TITLE
v1.9.2 Stacked Items Disappearing in Shelves

### ISSUE THREAD

**Issue by jyumai** [Nuchaz/BiblioCraft#245]
Why do stacked items placed in the shelves become single items when removed?

**Comment by Nuchaz** [comment]
You should be getting full stacks back. I always do on my setup. What version of forge are you running? What items are can you place that disappear? Are you on singleplayer or SMP?

**Comment by jyumai** [comment]
I am using forge 1.7.10-10.13.2.1291 on singleplayer. I actually tried to duplicate the bug a while ago but everything worked fine. I used modded items on the shelves (but again they seem to work fine now). Perhaps it was something to do with incomplete stacks in my inventory and them getting rearranged when I removed the items from the shelf. If I manage to duplicate the bug again I will let you know :)
