### ISSUE TITLE
Suggestion/Cosmetic: Support for metal decor

### ISSUE THREAD

**Issue by eruantien-hiraear** [Nuchaz/BiblioCraft#247]
While playing with Bibliocraft, I have noticed that sometimes wooden items and decorations don't always fit the theme of whatever I'm building. Would it be possible to make sets of shelves, chairs, tables, etc. that are made with metals (iron, gold, modded metals like copper and bronze) instead of wood? I'm not sure how much this fits the "theme" of Bibliocraft, but seeing that there's already metal lamps and stuff, and that the highlight seems to be "storing things pretty", I think this would be a welcome addition to your mod.

**Comment by Nuchaz** [comment]
It is funny you should mention this, I've been working on something that will make this possible. ;)

Coming soon: https://twitter.com/Mozzerello/status/571836802270674944

**Comment by eruantien-hiraear** [comment]
Wow, that looks really great! Now it's like, what, Carpenter's Bibliocraft or something? :O
can't wait 28/8 gr8 m8

**Comment by Nuchaz** [comment]
Thanks. :) 

Carpenter's blocks is definitely an inspiration.
