### ISSUE TITLE
Sword Pedestal should accept swords through item transport 

### ISSUE THREAD

**Issue by andrewring** [Nuchaz/BiblioCraft#249]
The sword pedestal is recognized as an inventory by things such as pipes, conduits and inventory cable, but you cannot move items in or out with them.  It would be nice to be able to automate without an autonomous activator. 

Observed in FTB Infinity 1.7 version 1.2.0

**Comment by Nuchaz** [comment]
I'll see about fixing that. Definitely a bug, they should accept swords from hoppers/pipes/etc.

**Comment by andrewring** [comment]
Thanks.  Love the mod, by the way.  :)
