### ISSUE TITLE
Seats emit redstone signal despite config

### ISSUE THREAD

**Issue by emperor06** [Nuchaz/BiblioCraft#250]
I have set ChairRestone to false in BiblioCraft.cfg but the seats still emit a signal when a player sits. Tested with BiblioCraft's oak seat and BiblioWoods Biomes O'Plenty Edition dark seat.

Minecraft 1.7.10
Forge 13.2.1291
BiblioCraft 1.9.2
BiblioWoods BiomesOPlenty 1.9

**Comment by Nuchaz** [comment]
I'll have a look at my code and see what happened. I must have derped somewhere.

**Comment by Nuchaz** [comment]
Yeah, that was definitely a derp on my part. This will be fixed in the next release.
