### ISSUE TITLE
Atlas Duplication Bug

### ISSUE THREAD

**Issue by ErdrickXLII** [Nuchaz/BiblioCraft#255]
I frequently get a client/server inventory desync when mouse-wheeling quickly past an Atlas in my hotbar causing there to appear to be two Atlases.  Forcing an update on the slot fixes it (picking it up, dropping it on the ground, etc.), but that's not the bug I'm here to report.

One time this happened, it replaced a Thermal Expansion Strongbox.  Knowing that it was the strongbox and not the atlas, I right-clicked to place it down without bothering to correct the desync.  The strongbox was placed correctly, but the atlas GUI also opened (the waypoint editing GUI as that was the last one I had open), except the was no map, not even a blank one, just the add/edit waypoint buttons in the top left and the mode switch in the bottom right.

I thought it was just a weird bug so I hit Escape, but then I still had the extra Atlas in the slot the strongbox was in.  It was not a desync, it was an exact duplicate of the original, including all of the waypoint compasses and extra blank maps stored inside.

**Comment by Nuchaz** [comment]
Is this on BiblioCraft v1.9.2? I thought I had this bug fixed, or at least I haven't been able to reproduce it since.

**Comment by ErdrickXLII** [comment]
Bah, I though I was on 1.9.2, but I was only on 1.9.1, seems fixed.  Sorry about that.
