### ISSUE TITLE
Crash with Furniture Paneler and Thaumcraft Greatwood planks

### ISSUE THREAD

**Issue by T4ge** [Nuchaz/BiblioCraft#259]
http://pastebin.com/47UNN6v9
Crash happened both while using GUI and not using the GUI
It accepts the framed block, but upon placing the plank it, the server crashes.
Also tested normal oak wood planks, crashed as well.

**Comment by Nuchaz** [comment]
Hmm, that definitely shouldn't be happening. Someone on the forum posted a similar crash too. I'll do some investigating and see if I can get this fixed real soon.

**Comment by T4ge** [comment]
Really appreciated, was so hyped for this when i saw it, been waiting for greatwood shelves for so long ^^

**Comment by Nuchaz** [comment]
I just released BiblioCraft v1.10.1, that should fix the crash. :)
