### ISSUE TITLE
BiblioCraft 10.0.1 - NullPointerException using unzipped resource packs with no custom painting directory

### ISSUE THREAD

**Issue by tidychips** [Nuchaz/BiblioCraft#262]
# Overview

BiblioCraft 10.0.1 will throw a NullPointerException when used in conjunction with unzipped resource packs that do not contain the BiblioCraft custom paintings directory.  This results in two issues:

1.  Unzipped resource packs without a BiblioCraft custom paintings directory cannot be loaded
2.  If an unzipped resource pack without a BiblioCraft custom painting directory was loaded prior to installing BiblioCraft, the Minecraft client will crash on start up.

The issue is minor, as it can be worked around by zipping the resource pack.

# Steps to Reproduce

1. Start with an empty forge 10.13.2.1320 profile and add BiblioCraft 10.0.1
2. Add an unzipped resource pack to the profile and remove the assets/bibliocraft/textures/custompaintings/ directory if it exists
3. Start minecraft, and attempt to load the resource pack
4. The following stack trace is printed to the log, and the resource pack is not loaded
5. If the resource pack is loaded before BiblioCraft is added to the profile, Minecraft will crash on startup with the same stack trace.

[Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.TextureStitchEvent$Post@46984524:
java.lang.NullPointerException: Registering texture
	at jds.bibliocraft.PaintingUtil.getListFromResourcePack(PaintingUtil.java:344)
	at jds.bibliocraft.PaintingUtil.getResourcePackPaintings(PaintingUtil.java:260)
	at jds.bibliocraft.PaintingUtil.getListOfPaintings(PaintingUtil.java:143)
	at jds.bibliocraft.PaintingUtil.updateCustomArtDatas(PaintingUtil.java:65)
	at jds.bibliocraft.EventResourcePackReload.ReloadResourcePackEvent(EventResourcePackReload.java:11)

# Analysis

It looks like this is due to the odd behavior of the Java [File.list()](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#list--) method.  If the directory does not exist, it will return null, rather than an empty array.  

This appears to cause issues in the PaintingUtil class when it iterates through the list of all files in the resource pack's assets/bibliocraft/textures/custompaintings/ directory.  There is no null check on the list method's return value, resulting in an uncaught NullPointerException.

However, this is mostly speculation on my part from examining the bytecode.

**Comment by Nuchaz** [comment]
Thats for being so detailed! This helps me a lot in tracking down and fixing this. It was brought up on the forum, but I hadn't been able to reproduce it yet.  From your analysis I think I know exactly where the problem is. You're right on, I made the assumption that if the File didn't exist, File.list() would return an empty array. This should be a pretty easy fix then.

**Comment by Nuchaz** [comment]
I just uploaded v1.10.2 to the website. That should fix the crash. I was unable to actually duplicate the crash on my system, but I've determined from the other crash logs that I believe this is happening on Java 8 while I am still running Java 7. So it seems the behavior of File.list() has changed between Java versions. Either way, the update should fix the problem. Let me know if it doesn't.

**Comment by tidychips** [comment]
Tested with the new 1.10.2 version and the issue is fixed.  All of my testing has been done on Java 8, so I'd wager you're right about the behavior difference between versions.  Glad I could help out with the issue, as I love the mod!

**Comment by Nuchaz** [comment]
:+1:
