### ISSUE TITLE
Bibliowoods Natura crash

### ISSUE THREAD

**Issue by Davografie** [Nuchaz/BiblioCraft#263]
I'm on 1.7.10 with Thermal Expansion and Bibliowoods Natura. When I create a Terrain Smasher; the terrain smasher has two unnamed items from Bibliowoods Natura in its augmentation tab. When I try to put one of these items in my inventory, the game crashes (and I have to set a back-up of my world to log in again)

**Comment by Nuchaz** [comment]
Hmm, thats an odd bug. There likely isn't anything I can do about that either. The newest version of BiblioCraft has a way to support basically any type of wood so I won't be updating the BiblioWoods anymore. So if it is much of an issue, I would consider phasing out BiblioWoods from your world and replace any of those blocks with the new framed versions covered in Natura wood planks.
