### ISSUE TITLE
BIblioWoods TFC - Minetweaker removes both recipes

### ISSUE THREAD

**Issue by Bunsan** [Nuchaz/BiblioCraft#270]
I'm attempting to remove some of the vanilla recipes from Bibliocraft in my TFC based pack, but doing a filtered removal for some items results in both the vanilla and TFC recipe being removed.  For example the oak furniture paneer works as expected with this script
```
recipes.removeShaped(<BiblioCraft:BiblioPaneler>, [[<minecraft:iron_ingot>, <BiblioCraft:item.FramingSaw>, <minecraft:iron_ingot>], [<minecraft:wooden_slab>, <minecraft:wooden_slab>, <minecraft:wooden_slab>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
```
But for the Framed furniture paneler it removes both the vanilla and the TFC version of the recipe with this script.
```
recipes.removeShaped(<BiblioCraft:BiblioPaneler:6>, [[<minecraft:iron_ingot>, <BiblioCraft:item.FramingSaw>, <minecraft:iron_ingot>], [<BiblioCraft:item.FramingBoard>, <BiblioCraft:item.FramingBoard>, <BiblioCraft:item.FramingBoard>], [<BiblioCraft:item.FramingSheet>, <BiblioCraft:item.FramingSheet>, <BiblioCraft:item.FramingSheet>]]);
```

I don't see a pattern of what works and doesn't. The cookie jar and typewriters work to remove just vanilla, but the sword pedestal does not. There are a lot more, but I haven't gone through them all yet.

**Comment by Nuchaz** [comment]
Hmmm, I have no clue why that isn't working. I might consider adding a config option to disable vanilla recipes just specifically for the TFC addon. Though technically, the regular recipes wont even work with TFC installed because much of the required stuff is missing. So I guess the only real reason to remove would be to clean up NEI recipe lists.

**Comment by Bunsan** [comment]
The reason it would be helpful was that many recipes are possible in my pack. I certainly can deal with it by re-adding the necessary recipes. However I reported it due to the strange inconsistencies, hoping it would be a straightforward fix.

**Comment by raymondbh** [comment]
@Bunsan use this script and hide the recipes instead of removing them...
https://github.com/raymondbh/InterConfig/blob/master/scripts/hidenei-bibliocraft.zs
