### ISSUE TITLE
Client side ignores Server side rejection of RIGHT_CLICK_BLOCK event

### ISSUE THREAD

**Issue by krwminer** [Nuchaz/BiblioCraft#271]
When a Forge PlayerInteractEvent , (RIGHT_CLICK_BLOCK), is rejected server side the client gets out of sync with the server. Also in some cases it allows the client side right click to make a permanent change, (Clock GUI and Draft Compass).

This was discovered when using MyTown2 protection which is a Server side only mod.

**Comment by Nuchaz** [comment]
Thats interesting. I've never had this happen before. Does this happen without the MyTown2 protection mod? Is that a pure forge server or is it one of the fancier ones? (I forget the names of the different ones)

**Comment by krwminer** [comment]
MyTown2 is a pure Forge server side protection mod. It is like MyTown & GriefPrevention plugins for Forge but also plugs all the holes that mods introduce.

The problem itself has to do with the Forge PlayerInteractEvent and was tested on a pure Forge server.

Not many people know that the Forge PlayerInteractEvent can be rejected server side, instead they do some things on the client or both the client and server. But it can be rejected server side and Forge does all the right things.

In particular, I noticed the Clock GUI would open up even when this event was rejected server side. Also the Draft Compass appears to make a change sever side when this event is rejected server side.

Let me know if I can help in any way and thanks for looking at this.
