### ISSUE TITLE
BiblioWoods TFC addon Plank Meta data lost

### ISSUE THREAD

**Issue by Bunsan** [Nuchaz/BiblioCraft#272]
The instance is running BiblioCraft[v1.10.3][MC1.7.10], BiblioWoods[TerraFirmaCraftV0.79.17][v1.0], [1.7.10]TerraFirmaCraft-0.79.17.645 and forestry_1.7.10-3.5.0.479-unstable; in a forge 1291 environment. If I craft forestry logs into planks the output slot shows the appropriate result, but when it is removed it has its meta data removed. For example Forestry:log1:0-3 to Forestry:log4:0-3 gives Forestry:planks:0-15 however any log placed in crafting grid will appear to give Forestry:planks with appropriate meta value, but when removed gives Forestry:planks:0. For Forestry:log5:0-3 to Forestry:log8:0-3 it does the same, but Forestry:planks2:0 is output. It is possible to get the planks via /give.

The same is true for vanilla log to plank crafting if the crafting recipe is enabled in the TFCRecipes.cfg. All logs are crafted into oak planks. I've tested and assure it only occurs with the BiblioWoods for TFC loaded.

**Comment by Nuchaz** [comment]
That is really odd. I don't do anything to that I know of that should even effect Forestry stuff. I just tested by adding forestry to my terrafirmapunk instance and I couldn't reproduce the issue. The forestry logs seem to craft to planks just fine and retain meta-data.

**Comment by Bunsan** [comment]
I know it was happening in a clean instance, but now I can't reproduce. Apologies, I blame sleep deprivation. If I can reproduce I'll comment here. Might as well close this.
