### ISSUE TITLE
[Suggestion] Align to center option

### ISSUE THREAD

**Issue by kimfy** [Nuchaz/BiblioCraft#273]
An align to center option on the Fancy Signs would be great. Select a line and hit a button to align line to center.

**Comment by Nuchaz** [comment]
I've been wanting to do something like that. I've had this requested a number of times. It is just much easier said than done. So, this might happen eventually, if I can figure out how to make it happen with the setup I have.

**Comment by Nuchaz** [comment]
Added in BiblioCraft versions 2.0.0 and newer
