### ISSUE TITLE
Slotted Book allows players to duplicate items!

### ISSUE THREAD

**Issue by translayton** [Nuchaz/BiblioCraft#276]
Hi everyone,
it is possible to duplicate items using the Slotted Book item. 
You only have to put an item into the book and save it; then, without closing the book, drop it out of your inventory, took the item and close the book.
Pick up the book and open it: it saved the item you put previously, but you also have the item in your inventory.

Also, i'm trying to block the recipe using MineTweaker3, but the Slotted Book apparently has no name :/
I tried to use BiblioCraft:SlottedBook or similar, but it doesn't work. Could you say me the name of the item?

Hope you read and fix this soon as possible, thanks!

I'm running BiblioCraft[v1.9.2][MC1.7.10]!

I'm uploading a video where I replicate the bug: http://youtu.be/qrp33NtUosg

**Comment by aadeg** [comment]
I have this issue too.

**Comment by Claycorp** [comment]
Yikes! Super easy to dupe. Hope this is fixed soon!
The ID you need is BiblioCraft:item.SlottedBook 

You can find item ID's by pushing F3+H With D3Core, NEI and possibly some other mods installed. (Not sure if it shows in vanilla.) Else with MineTweaker you can do /mt hand and it will give you the information you need.

**Comment by Nuchaz** [comment]
Hmmm, this definitely needs to be addressed. I'll look into doing something about this soon.

**Comment by Nuchaz** [comment]
I tested and easily duplicated the issue so I decided to just lock the slot so the player cannot pick up the slotted book when it is open, much like I do the atlas. After I look into and try to fix a couple other issues I'll try to get a bugfix update out hopefully by this weekend or over the weekend.

**Comment by translayton** [comment]
@Claycorp Thank you very much for the ID, it worked! :D 
It seems that my server hates MineTweaker lol, every time I tried using /mt hand the server said "An unknown error occurred while attempting to perform this command!"

@Nuchaz Thank you, I hope you'll be able to fix it :D

**Comment by Nuchaz** [comment]
Fixed in 1.10.4. You can no longer click the slotted book item when it is open. That should solve this issue.
