### ISSUE TITLE
Version checking

### ISSUE THREAD

**Issue by Claycorp** [Nuchaz/BiblioCraft#277]
Please add the applicable bit of code to your version checker.
http://pastebin.com/J6JCsgJE

This will stop version checking in any Curse instances as it handles all version checking against Curseforge on its own and makes your version checking redundant.

Thanks!

**Comment by Nuchaz** [comment]
Ok, can do. Definitely makes sense why this is a good idea.

**Comment by Nuchaz** [comment]
Added in 1.10.4.
