### ISSUE TITLE
Swapping Out Applied Canvas in Painting Frame Crash

### ISSUE THREAD

**Issue by haighyorkie** [Nuchaz/BiblioCraft#278]
http://pastebin.com/vCeRSLD0

Using the latest version of Bibliocraft (v1.10.3)
If you need any further info please ask :) It was another user on the server who crashes with this crash whenever they enter the area so I apologize for the sketchyness of my info!

**Comment by Nuchaz** [comment]
Hmmm, definitely not good. Is this a custom painting, an included bibliocraft painting or a vanilla painting?

**Comment by haighyorkie** [comment]
This is the details I got about it:

Wall: mixture of stone bricks, cracked stone bricks, and (Tinker's Construct) fancy stone bricks
Painting: size 7x7, resolution 128x128, scale 7x7

Unfortunately, I can't remember which painting was applied to the canvas, other than that it was one from the Bilbliocraft tab. Also, not sure if I was using a borderless frame or a dark oak frame.

I had already placed another canvas with a Bibliocraft painting applied in the bottom-left corner of the frame, and when I took it out and attempted to put the new one in, my client crashed with an error in the Bibliocraft painting renderer.

**Comment by Nuchaz** [comment]
Thanks for the additional details. I think I understand what might be happening. It sounds like the painting frame didn't reset all its data when the old painting canvas was removed and the new painting canvas doesn't have the data the painting frame is looking for.

I'll see what I can come up with for a fix.

**Comment by Nuchaz** [comment]
I added a fix in v1.10.4. This issue shouldn't happen again hopefully. Where it has already happened though, you may have to use something like MCEdit to manually remove that block (looks like its @ (1045,78,-3855))
