### ISSUE TITLE
[Suggestion] Rename, color or texture Creative-mode Oak Bookcase

### ISSUE THREAD

**Issue by Haggle1996** [Nuchaz/BiblioCraft#279]
Simple request -- can you rename or recolor (purple-tinge) the creative-mode Oak Bookcase? In NEI, it's named Oak Bookcase, but calling it Creative Bookcase (dropping the oak) would reduce confusion in NEI. I had a user of my pack complain the Oak Bookcase was uncraftable and they were just clicking on the creative one. :)

**Comment by Nuchaz** [comment]
Thats a good idea. I'll see what I can do. I've actually been caught off guard myself several times by that exact issue.

**Comment by Nuchaz** [comment]
In v1.10.4 I did a couple of tweaks to make it looks a little different (less books on the shelf in the item icon) and changed the text color of "creative mode only" to light purple so it stands out better. So hopefully that helps.

**Comment by Haggle1996** [comment]
Thanks! You are awesome!
