### ISSUE TITLE
Slotted Book - Dupe Bug

### ISSUE THREAD

**Issue by SirWilli** [Nuchaz/BiblioCraft#284]
BiblioCraft[v1.10.2][MC1.7.10]
Video: https://youtu.be/NXoJUdf3dEA (Please remove the link after you have seen it.)

**Comment by Nuchaz** [comment]
Old issue, fixed in newer version. Update your BiblioCraft.

**Comment by SirWilli** [comment]
Ok, sorry, didn't knew that.
