### ISSUE TITLE
Feature Request: Config option for Auto-Public book creation

### ISSUE THREAD

**Issue by PitchBright** [Nuchaz/BiblioCraft#286]
We have some people that write books, and some people that operate printing presses. The printing press operators are unable to create chases for the books, if they weren't the authors. The only way around it seems to be to op them so they can go into creative mode, and change the Private setting on the book to public.

Can we please have an option in the config to allow us to set all written books to public by default?

**Comment by Nuchaz** [comment]
Yeah, I'll see about doing that. For some servers I know having books set to private is more ideal, but I can definitely understand why in others you may want public as the default. A config option should be pretty easy to add.

**Comment by PitchBright** [comment]
Awesome, thanks dude!

**Comment by PitchBright** [comment]
Not to pester ya, just a bump, since I've got you looking at a few other things at the same time. This one has definitely become a problem for us, now that the guy that wrote all our server's lore and storybooks has left the team, and the new Scribe wants to copy the written archives to fill the Library's shelves. He can't use any of the books that were authored by other people, on the Typesetting table, since the books are default to Private.

**Comment by Nuchaz** [comment]
I'll throw this in with the 1.12.0 update. I think I overlooked this the last few updates. 

It might be worth mentioning too, if you go into creative mode, all the books will show up on the typesetting able regardless if it is public or private, so that is a good way to get in there and change some to public if you need to.

**Comment by PitchBright** [comment]
Thats what I thought too, and did back when I reported... But it didn't happen for me this time around. I probably derped and wasn't in Creative. I'll test it again when I wake up. Eitherway, thanks for tackling this!
