### ISSUE TITLE
Desk Things

### ISSUE THREAD

**Issue by OmegaRenan** [Nuchaz/BiblioCraft#288]
the lexica botania nor the agricultural journal from agricraft do not open wen they are in the desk

**Comment by Nuchaz** [comment]
Unfortunately I can't get the lexica botania working. I had tried in the past and the only thing I could get on the desk is crashes.  I haven't tried agricraft, I might give that journal a go and see if that is something that I can add. 

I basically have to add support for books on the desk on a case by case basis. If a mod strays much from vanilla in how they deal with opening books then I likely cannot make it work on the desk.

**Comment by InfinityRaider** [comment]
@Nuchaz do you have an API that I can use so I can make it work from my side?

**Comment by Nuchaz** [comment]
Afraid I have no API at this point. That would be a good thing to add to an API if I were to make one. I would actually like to put together an API at some point.
