### ISSUE TITLE
Bibliowoods TFC seems to be incompatible with 0.79.18+

### ISSUE THREAD

**Issue by AussieWarGod** [Nuchaz/BiblioCraft#290]
Crash on client join. SP works fine. Due to adding of anvil super seeding in new update.

http://pastebin.com/PJ6hKwx5

**Comment by Nuchaz** [comment]
This was fixed a couple weeks ago, please update your BiblioWoods for TerraFirmaCraft to v1.1. You can find downloads @ bibliocraftmod.com or on curseforge.
