### ISSUE TITLE
No instanceof checking before casting tile entities.

### ISSUE THREAD

**Issue by CovertJaguar** [Nuchaz/BiblioCraft#291]
I recently had a user of Railcraft report the following crash log to me:
https://drive.google.com/file/d/0B2R1bLlG2_JCWmx5NEZ1dlRCd2pMbXZaQzlOQkZUczU4US1r/view

Me and Player weren't able to track down how BlockTable.getLightValue() got called in such a way that it found the wrong tile entity, but we eventually just concluded that whatever the cause, you should always instanceof check before casting Tile Entities anyway.

So just passing this along.

**Comment by Nuchaz** [comment]
Thanks. I'll see about doing that before my next release, esp for the light value methods. I did start checking the instanceof for tiles on most of the newer blocks, I just never went back and updated old code to follow suit.
