### ISSUE TITLE
Please set your inventory names or localize them.

### ISSUE THREAD

**Issue by Claycorp** [Nuchaz/BiblioCraft#292]
HoloInventory uses this name to display what inventory you look at.

String getInventoryName(); should return the name or localized name.

http://i.imgur.com/n6qlSc0.png

**Comment by Nuchaz** [comment]
I'll see about getting that done before my next update. That is the first instance where I've seen that inventory name actually matter, hence the reason I never really bothered to localize the names.

**Comment by Claycorp** [comment]
Thanks!

**Comment by Nuchaz** [comment]
Localized the names, will be in next update, hopefully sometime this weekend
