### ISSUE TITLE
Crash with BoP bibliowoods

### ISSUE THREAD

**Issue by TheSlimeMan** [Nuchaz/BiblioCraft#295]
so yes, added BoP and Bibliowoods BoP and this happens :O
----------
http://pastebin.com/bkjvWXPd

**Comment by Nuchaz** [comment]
It doesn't look like you have BiblioCraft installed. the BiblioWoods packages require BiblioCraft to be installed as well.

**Comment by TheSlimeMan** [comment]
:| wtf was I thinking
