### ISSUE TITLE
[Request]TFC Bibliowoods - Hide Bibliocraft NEI items/blocks

### ISSUE THREAD

**Issue by raymondbh** [Nuchaz/BiblioCraft#299]
An option in the configuration to hide all original Bibliocraft items in NEI when using TFC Bibliowoods.

**Comment by Nuchaz** [comment]
I'll see about doing that sometime. A few of the original things are still relevant so I will have to setup some special cases, but it shouldn't be too hard I don't think.

**Comment by raymondbh** [comment]
Would be awesome, then I don't need to use Minetweaker to do it.
