### ISSUE TITLE
Thaumcraft jar label

### ISSUE THREAD

**Issue by Corvorosso** [Nuchaz/BiblioCraft#307]
i have an issue when i place some jars in the potion shelfs, the labels of the jars are not visible because the jars itself turn sideways and the label remain covered by other jar. Long story short i can't place jars with the label facing me.
I don't know if this is a bibliocraft issue or maybe is caused by other mod interaction, but if someone have any advice it is welcome 
thank you
and sorry for bad english :P

**Comment by Nuchaz** [comment]
Which way are the jars rotated? If you are facing the potion shelf, which way is the label turned?
This is an odd problem that comes up from time to time, but it always seems to be facing forward on my setup. What versions of forge and thaumcraft are you using? I'll try to test with the same versions to see if it will show up for me then. If nothing else, I'll consider a config option you can change to fix it, that way if it is different on different setups, it can easily be tweaked.
