### ISSUE TITLE
Feature Request: Texture whitelist for Paneler

### ISSUE THREAD

**Issue by PitchBright** [Nuchaz/BiblioCraft#317]
I think a lot of admins would like to be able to limit what textures people make their furniture out of, especially servers that focus on realism. If we could have a config file for a whitelist for what blocks we would like to allow people to use in the Paneler that be great.

Thanks!
-Pitch

**Comment by Nuchaz** [comment]
I might could do that sometime in the future. I think that would take a good bit of work to get it working.

**Comment by PitchBright** [comment]
Ah bummer, I was hoping it would be an easy thing to implement. It's the only reason I've disabled the framed stuff on our server, if not for that, I would love to use them. I fear the day a kid furnishes his house out of pumpkin textured desks and chests xD.
