### ISSUE TITLE
Feature Request: Config option to disable crafting from Recipe Books

### ISSUE THREAD

**Issue by PitchBright** [Nuchaz/BiblioCraft#318]
The new Crafting from Recipe Books feature kills the need and use of a Fancy Workbench. Players feel like there's no need to go to their workstation to do their crafting anymore. It also pretty much takes the "craft" out of "Minecraft", at least to the Survival players. Creative players don't care because they just spawn stuff in, so they don't use the recipe books anyway, I'm sure.

Can we please have an option to disable crafting from Recipe Books? Pretty please! :-)

**Comment by Nuchaz** [comment]
That should be easy enough to add. I'll look into it.

I don't really see how it kills the need for a fancy workbench when you have to have a fancy workbench to make recipes books. I also don't really see how it removes the "craft" from "minecraft". That is a bit dramatic. You still have to have the ingredients and you have to craft the recipe book to begin with. I think it plays a useful role with some of the more complicated multi-part recipies but they seem cumbersome to use has a primary means of crafting to me. But that just has to do with how I like to play the game. I understand if it doesn't fit you style of play so I'll see about adding an option.

**Comment by PitchBright** [comment]
True enough about the Fancy Workbench. I didn't want to say Crafting Table because I didn't want you to like the idea that it would make it obsolete, and int-turn, make Fancy Workbench more important… lol. Also, you're probably right about the exaggeration of it, in the grander scheme of things. I think what we're doing necessitates people to work in specific locations, rather than having portable crafting… so that's where my server would be impacted by the Recipe Book Crafting method, where other server wouldn't. But if you're willing to do that disable option for us, that's awesome! Thanks so much.

**Comment by Nuchaz** [comment]
I'm adding this for the 1.12.0 update I am working on.
If it is only disabled on the server side, the client will still see the button, but pressing the button will just inform them that crafting with recipe books is disabled. It will have to be disabled client side as well to disable the button from showing up.

**Comment by PitchBright** [comment]
Awesome! Thanks so much!
