### ISSUE TITLE
Language file support for Stockroom Book

### ISSUE THREAD

**Issue by PitchBright** [Nuchaz/BiblioCraft#319]
The Stockroom Book looks awesome. Pertaining to the location of items, I see that the Chest details specify the Block's (Chests/Container) modname, and X-Y-Z co-ordinates. For people that are using resourcepacks, the containers name might not reflect what the in-game name of the container is.

Is it do-able to have that changed so that it uses the Lang name, instead of the blockname?

**Comment by Nuchaz** [comment]
It should already work like that, if not I don't think there is anything I can do to fix it. I get an unlocalized inventory name (which is the only name I really have access too) then I use the vanilla minecraft methods to translate it. I would expect the vanilla stuff to get the correct name based on language files and resource packs.
