### ISSUE TITLE
Dupe Bug with Slotted Book

### ISSUE THREAD

**Issue by HandGrenade** [Nuchaz/BiblioCraft#324]
Hey,

There seems to be a duplication bug with the slotted book. It is simple to reproduce (but from what I can see, needs at least 1 other mod to work). You must first open the book, place in your item of choice, Save it, close your book, open it again, and while it is open in your inventory, have an external source remove it from your inventory. The gui will not close, and you can remove the item, and then get the book from wherever it went and have 2x the item.

My description of the duplication may not be the best, but here is an example using the PIM from OpenPeripheralAddons: https://www.youtube.com/watch?v=hZXCu_Fmdvo

Thanks!

**Comment by Nuchaz** [comment]
Thanks for the report. I'll look into this.

**Comment by xSable** [comment]
As I can see this was never closed, let me tell you it's still an issue in the latest version for 1.7.10. 
BiblioCraft v1.11.5

Don't know about 1.8

This can be reproduced without any other mods.

Open the Slotted Book
Put item in
Save and close book
Open book again
Remove item
Die without closing GUI

Item will drop and so will book with item in it.

**Comment by Nuchaz** [comment]
I thought I had this taken care of. I left this report open cause I was never 100% sure. Thanks for the report. I'll look into this. I'll look at this in the 1.8.9 version too.

**Comment by xSable** [comment]
Sweet, hope you find a fix.

**Comment by Eufranio** [comment]
Fixed?

**Comment by Eufranio** [comment]
Hmm, no it is not fixed in 1.7.10 yet :/

**Comment by Nuchaz** [comment]
ok, I got this fixed. The problem carried through to the newest versions too. I will put out a version for 1.7.10 in addition to 1.10.2 and 1.11.2 that all have this fix. Coming soon.
