### ISSUE TITLE
IC2 Chainsaw sound loop in Tool Rack

### ISSUE THREAD

**Issue by JasonMcRay** [Nuchaz/BiblioCraft#329]
When you put an IC2 Chainsaw into tool rack by right clicking the Chainsaw into it, it will keep playing the "motor" sound. Just holding the Chainsaw in your hand causes the sound to play.

When you open the Tool Rack interface (by empty hand clicking) and you insert the Chainsaw manually into the slot, the sound is not happening.

**Comment by Nuchaz** [comment]
This has actually been a problem since the early days of BiblioCraft and I never could figure out a way to fix it other than, as you mentioned, opening the GUI and placing it in that way.
