### ISSUE TITLE
Big Books and persistance

### ISSUE THREAD

**Issue by joflashstudios** [Nuchaz/BiblioCraft#332]
I've run into two problems with Big Books:
1. Resizing the Minecraft window while editing a Big Book erases all edits.
2. Sometimes, edits are discarded when clicking "save."

I haven't been able to pin down exactly what causes 2. It's incredibly frustrating when the book deletes what you just wrote.

**Comment by Nuchaz** [comment]
oh wow, that is terrible. I think I have an idea on how I can fix #1 but I'm not sure why #2 is happening. I'll investigate when I got some time.

**Comment by Nuchaz** [comment]
I have fix in place for the next release which will be v1.11.3 for the first problem. I haven't made any headway on the second problem. If you see any errors or messages in your logs when that happens, let me know, maybe something there can clue us in.
