### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by runescapejon** [Nuchaz/BiblioCraft#333]
how do i fix this crash report http://pastebin.com/mhg7dY5H
keep happening to my server

**Comment by Nuchaz** [comment]
Hmmm, that definitely shouldn't be happening. It looks like something is happening when something is tossed on the ground. Any idea what it might be that is being tossed so I can try to reproduce it?

**Comment by runescapejon** [comment]
I have no idea i have sent my staff members to keep on eye out for bibilocraft mod

**Comment by runescapejon** [comment]
This crash report keep happening i have drop every item and nothing happens are you sure its something do with tossed on the ground?

**Comment by Nuchaz** [comment]
I'm pretty sure, judging by the crash report, it is happening during an EventItemToss which means it is happening when either the drop button is pressed or it is thrown out of an inventory when a gui is open. Unless another mod is triggering the event in some weird circumstance. 

It looks like it is crashing when I try to get the unlocalized name of the itemstack that is being tossed on the ground by a player. I'm not sure why it would do that. I can't seem to figure out how to reproduce it on my end.
