### ISSUE TITLE
BiblioCraft doesn't support the changes to woods in Forestry 4.0

### ISSUE THREAD

**Issue by Parker8283** [Nuchaz/BiblioCraft#334]
Forestry 4.0 just moved out of beta recently, and with the changes to the woods in Forestry, ~~BiblioWoods Forestry Edition is no longer compatible.~~ BiblioCraft doesn't seem to like them when used with the Furniture Paneler.

See https://github.com/ForestryMC/ForestryMC/issues/869

**Comment by Parker8283** [comment]
Upon seeing that you will no longer be updating BiblioWoods, support for Forestry's new woods for the Paneler should've been what this issue was for.

**Comment by mezz** [comment]
BiblioCraft is currently getting the icon from the block, but this doesn't work for blocks that depend on tile entities for their icon.
You can get the correct icon from `Item.getIcon(ItemStack stack, int pass)`
I just pushed a change to [the latest Dev version of Forestry](http://jenkins.ic2.player.to/job/Forestry_Dev/) that should allow this to work.

**Comment by Nuchaz** [comment]
Thanks mezz. I'll look into fixing this as soon as I get some time.

**Comment by Nuchaz** [comment]
I think I got a fix worked out in my dev setup. I am going to do null checks on both block and item icons this time too so it shouldn't crash regardless of what mods do with their icons in the future. Expect a fix in the next release, which will be v1.11.3
.

**Comment by mezz** [comment]
Cool thanks! Forestry 4.1 was just released as stable so it will support the new change.

**Comment by JasonMcRay** [comment]
@Nuchaz Do you plan updating the Bibliowoods to support the Forestry 4.x? None of the Forestry/Bibliowoods items are craftable currently.

**Comment by Nuchaz** [comment]
Not likely no, since the BiblioWoods addons have been superseded by the Furniture Paneler block. You can accomplish the same looks (and much much more) with the furniture paneler.
