### ISSUE TITLE
TerraFirmaCraft containers don't tick for Heat/Decay

### ISSUE THREAD

**Issue by AnodeCathode** [Nuchaz/BiblioCraft#337]
Wonder if we could have the Biblio containers tick for Heat/Decay when used with TerraFirmaCraft.

Just needs an UpdateEntity override calling:

TFC_Core.handleItemTicking(this, this.worldObj, xCoord, yCoord, zCoord);

For the TFC containers. Would be really nice as currently it's a rather huge loophole in a fairly key TFC mechanic.

Thanks!

**Comment by Nuchaz** [comment]
I'll look into adding this. It should be no problem. Yeah, I totally understand about that being an issue. I had actually thought about wanting to add ticking behavior for that awhile back, but wasn't sure how to approach. Thanks for sharing an easy way to approach it.

**Comment by AnodeCathode** [comment]
Yeah in the meantime we're just ASMing it into the Framed Chest TE from our modpacks core utility mod. Works but would rather have it only run every 200 ticks or so. Just wanted to close a big loophole in the decay/heat mechanics. :)

Thanks for having a look at it.
