### ISSUE TITLE
Atlas Menu Bug

### ISSUE THREAD

**Issue by Shadow-of-Christ** [Nuchaz/BiblioCraft#338]
Has anyone ran into this problem? I've actually never gotten to get the Atlas to work correctly.

![screen shot 2015-10-20 at 9 50 32 pm](https://cloud.githubusercontent.com/assets/8767029/10627439/05e43dc8-777f-11e5-8786-e8f489a0d445.png)

**Comment by VT-14** [comment]
Try turning off your texture pack.  The one I use does something similar with a Blood Magic Teleposer and a handful of Mekanism GUIs (though, no problems with Bibilocraft so far).

**Comment by Nuchaz** [comment]
That looks like a texture pack issue. It looks like your texture pack had added support for the atlas when I had a creative-only temporary version of the atlas. Either disable your texture pack, update it if there is a newer version with proper atlas support, or remove the atlas related textures from the pack to fix.
