### ISSUE TITLE
SextiarySector2 and BiblioWoods[Forestry] [Mod Conflict]

### ISSUE THREAD

**Issue by Nikslg** [Nuchaz/BiblioCraft#342]
Somehow BiblioWoods conflict with mod named SextiarySector2...
I posted that in forum's topic but no answer tho...

Quote:
Ahm... I am not sure if i should post it here but BiblioWoods[Forestry][v1.7] is getting crash when used japanese mod named:
SextiarySector2 (mod for MCEconomy2 that adds currency to the game)
I can upload those two just for testing.
We really wanna use both of them.

https://github.com/shift02/SextiarySector2/files/47324/crash-2015-11-30_16.44.15-client.txt

**Comment by Nuchaz** [comment]
I can't see any reference to BiblioCraft or BiblioWoods in the crash log so I have no idea what is going on. I would recommend skipping BiblioWood Forestry edition and just using the Furniture Paneler from BiblioCraft. It can accomplish the same goal (plus so much more). The furniture paneler is kind of the universal replacment for all the BiblioWoods stuff.
