### ISSUE TITLE
Feature request: Support for Pam's HarvestCraft

### ISSUE THREAD

**Issue by AngleWyrm** [Nuchaz/BiblioCraft#353]
The mod [Pam's HarvestCraft](https://github.com/MatrexsVigil/harvestcraft) adds bottles of drinks, such as lemonade, cactus fruit juice and so on. 

If it isn't too boring, could the Potion Shelf support adding such drinks?

**Comment by Nuchaz** [comment]
Improved support for pams stuff on potion shelves will be much improved in the next release.
