### ISSUE TITLE
[1.7.10] Unknown recipe class!

### ISSUE THREAD

**Issue by MrBloodowrth** [Nuchaz/BiblioCraft#357]
`[FML]:   Unknown recipe class! jds.bibliocraft.BiblioSpecialRecipes Modder please refer to net.minecraftforge.oredict.RecipeSorter
`
BiblioCraft[v1.11.4][MC1.7.10]
forge-1.7.10-10.13.4.1614-1.7.10-universal

Thank you for your time.

**Comment by Nuchaz** [comment]
Fixed in BiblioCraft v1.11.5
