### ISSUE TITLE
Recipes registered in PreInt phase

### ISSUE THREAD

**Issue by 31trainman** [Nuchaz/BiblioCraft#358]
Im noticing this error about recipes being registered in preint phase for your mod http://pastebin.com/UHGcWZxH

Latest Bibliocraft and its addons
Mod list: http://pastebin.com/ss7RbZ2k

Forge 1614 mc 1.7.10
Java 8 update 91
Mac os x 10.11.4

**Comment by 31trainman** [comment]
Upon testing certain items recipes can't be seen in nei via the r key

**Comment by AnrDaemon** [comment]
Why you are still using bibliowoods? These addons were deprecated over a year ago.

**Comment by 31trainman** [comment]
I'm still on 1.7 till all the new mc version non sense gets cleared up

**Comment by AnrDaemon** [comment]
It was deprecated over a year ago, for MC 1.7.

**Comment by 31trainman** [comment]
Did you see what my problem is?
