### ISSUE TITLE
Crash with Fancy Workbench

### ISSUE THREAD

**Issue by ExcitedName** [Nuchaz/BiblioCraft#363]
I created a recipe book for a recipe from a mod I wrote. Crashed when trying to load grid with items from inventory using the button. It worked for one my recipes but not the other. I reproduced the crash a few times a looked at the log. I have a feeling this: "at java.lang.String.matches(Unknown Source) ~[?:1.8.0_66]" may have something to do with my mod. I have been having crafting issues with it and haven't been able to figure it out. So I have a feeling it's me. But I'm new to this. lol Great mod by the way. I have known of it for a while but am just now checking it out. I cannot see my self playing with out it now. lol
http://pastebin.com/TTSaRF3B

**Comment by Nuchaz** [comment]
I'll have a look at this when I get some time.
