### ISSUE TITLE
I can't delete Waypoint 0 from the Atlas

### ISSUE THREAD

**Issue by EzerArch** [Nuchaz/BiblioCraft#366]
I could create lots of waypoints on the map:

![2016-07-09_17 45 51](https://cloud.githubusercontent.com/assets/6743303/16710206/28ebfe44-45fd-11e6-8bf1-c915f2a11985.png)

I could remove all waypoints from the map...
![2016-07-09_17 47 46](https://cloud.githubusercontent.com/assets/6743303/16710214/40dd1baa-45fd-11e6-9899-9858ca61adae.png)

...except the 1st one, waypoint 0:
![2016-07-09_17 46 25](https://cloud.githubusercontent.com/assets/6743303/16710216/4f45572a-45fd-11e6-9581-6e3d281c9155.png)

...the Delete button plays the "click" sound but does nothing.

Reproducible on the other maps.

Using v1.11.5.

**Comment by Nuchaz** [comment]
I'll have a look at this. I am currently working on the Atlas for 1.8.9 and I'll make sure this is fixed in future versions.

**Comment by Nuchaz** [comment]
This turned out to be an issue where I had a  "> 0" thing happening and it should have been ">= 0".
I've fixed this in my 1.8 version I am working on and when ahead added a fix to my 1.7.10 code. I may release a final 1.7.10 bugfix release at sometime. I don't have a timline on that though yet since my focus is the 1.8.9 update and forward.

**Comment by Natesky9** [comment]
I've encountered this bug as well, and found this thread. I can't seem to delete *any* waypoints that I make

**Comment by Ravin890** [comment]
Natesky what version of minecraft and bibliocraft?

**Comment by Natesky9** [comment]
1.7.10, latest version for this version of Minecraft. I can't seem to be
able to delete any waypoints at all. Unless I'm missing something

**Comment by Nuchaz** [comment]
This will be fixed in the next release (coming soon) which will include a new version for minecraft 1.7.10,

**Comment by Natesky9** [comment]
thanks, bud! Hearts for the 1.7.10 support!

**Comment by EzerArch** [comment]
@Nuchaz, you real MVP! 🥂
