### ISSUE TITLE
Freezing and Unable to move

### ISSUE THREAD

**Issue by McBossKiller** [Nuchaz/BiblioCraft#379]
I am not sure if this is a problem with your mod or JEI, but when I look up the name of a bibliocraft item or block in JEI I Freeze and Lag to death, I have no movement, and has crashed my computer twice. I am guessing that the textures of the items in JEI of bibliocraft objects cause this to happen. Is this a compatibility issue with the two mods, using latest 1.8.9 versions of both mods.

**Comment by McBossKiller** [comment]
This has just happened to me when i disabled the use of JEI, just making a bibliocraft chair crashed my computer, not Minecraft though...

**Comment by Nuchaz** [comment]
Hmm, that is odd. I've been using JEI myself and my experience is none of my stuff renders in JEI, it is just invisible until I hover over that object with my mouse. Do you get any kind of crash log or errors in the console when it crashes?
I'll look into this some more and see if I can figure anything out.

**Comment by McBossKiller** [comment]
My whole computer Crashes, The blocks are not invisible, being about 1 sec in a jei menu with a bibliocraft item or block showing blows up my computer. I get no crash reports and my logs and saves refresh to about 10 minutes before the crash. Optifine somewhat delays the crash, but still causes this to happen. My guess is some sort of Rendering issue, I only have 4 mods installed with bibliocraft, optifine, jei , inventory tweaks, iron chests. If there is anything you still need to know, I practically told you everything, FPS does seem to go crazy before i crash, it goes from insanely high numbers to numbers like 1 and 0 constantly.
