### ISSUE TITLE
Crash: java.lang.NullPointerException: Tesselating block in world

### ISSUE THREAD

**Issue by squirrelkiller** [Nuchaz/BiblioCraft#381]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  BCModPlugin (zz-backpacks 1.8.9 - 3.1.0.jar)
  Java8CheckerCoremod (Pixelmon-1.8.9-4.3.0-beta4-universal.jar)
  MalisisCorePlugin (malisiscore-1.8.9-2.1.6.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 06/08/16 9:19 PM
Description: Tesselating block in world

java.lang.NullPointerException: Tesselating block in world
	at jds.bibliocraft.models.BiblioModelWood.getModel(BiblioModelWood.java:86)
	at jds.bibliocraft.models.BiblioModelWood.handleBlockState(BiblioModelWood.java:215)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:152)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:93)
	at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:705)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:194)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:905)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1287)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1058)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at jds.bibliocraft.models.BiblioModelWood.getModel(BiblioModelWood.java:86)
	at jds.bibliocraft.models.BiblioModelWood.handleBlockState(BiblioModelWood.java:215)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:152)

-- Block being tesselated --
Details:
	Block type: ID #207 (tile.BiblioCraft:BookcaseCreative // jds.bibliocraft.blocks.BlockBookcaseCreative)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (-74,65,262), Chunk: (at 6,4,6 in -5,16; contains blocks -80,0,256 to -65,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:93)
	at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:705)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:194)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:905)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1287)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['squirrel_killer'/513849, l='MpServer', x=-53.24, y=65.00, z=287.45]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -126.00,88.00,-431.00 - World: (-126,88,-431), Chunk: (at 2,5,1 in -8,-27; contains blocks -128,0,-432 to -113,255,-417), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 4862039 game time, 329735 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 60 total; [EntityPixelmon['Pupitar'/517507, l='MpServer', x=-90.50, y=12.97, z=353.50], EntityPixelmon['Swinub'/516225, l='MpServer', x=-76.06, y=64.50, z=235.75], NPCChatting[''/514063, l='MpServer', x=-78.50, y=65.00, z=249.50], EntityPixelmon['Octillery'/517141, l='MpServer', x=43.21, y=53.37, z=331.72], EntityPixelmon['Goldeen'/517139, l='MpServer', x=23.50, y=57.00, z=320.61], EntityPixelmon['Swinub'/516752, l='MpServer', x=-112.38, y=65.00, z=233.56], NPCChatting[''/514463, l='MpServer', x=-67.19, y=65.00, z=265.44], NPCChatting[''/514462, l='MpServer', x=-69.03, y=65.00, z=266.69], NPCChatting[''/514461, l='MpServer', x=-77.50, y=69.00, z=265.50], NPCChatting[''/514460, l='MpServer', x=-76.50, y=65.00, z=265.50], EntityPixelmon['Piloswine'/517401, l='MpServer', x=-110.50, y=64.97, z=354.50], EntityPixelmon['Piloswine'/517400, l='MpServer', x=-113.50, y=64.97, z=353.50], EntityPixelmon['Gastly'/517031, l='MpServer', x=-30.50, y=23.00, z=358.50], EntityPixelmon['Magikarp'/517286, l='MpServer', x=-150.50, y=58.00, z=292.50], EntityPixelmon['Magnemite'/517284, l='MpServer', x=-116.97, y=66.50, z=304.72], EntityPlayerSP['squirrel_killer'/513849, l='MpServer', x=-53.24, y=65.00, z=287.45], NPCShopkeeper[''/514464, l='MpServer', x=-50.50, y=65.00, z=258.50], EntityPixelmon['Geodude'/515886, l='MpServer', x=-16.50, y=51.00, z=263.50], EntityPixelmon['Joltik'/517166, l='MpServer', x=-61.50, y=34.00, z=326.50], EntityPixelmon['Magikarp'/517290, l='MpServer', x=-151.50, y=57.69, z=294.11], EntityPixelmon['Seel'/517558, l='MpServer', x=-149.50, y=64.00, z=212.50], EntityPixelmon['Swinub'/517557, l='MpServer', x=-88.66, y=69.97, z=286.50], EntityPixelmon['Swinub'/517556, l='MpServer', x=-91.22, y=70.00, z=286.50], EntityPixelmon['Roggenrola'/517553, l='MpServer', x=-66.50, y=16.97, z=245.50], EntityPixelmon['Boldore'/517183, l='MpServer', x=-85.50, y=11.00, z=365.50], EntityPixelmon['Zubat'/517052, l='MpServer', x=7.75, y=39.00, z=212.88], EntityPixelmon['Unown'/517049, l='MpServer', x=3.50, y=37.00, z=208.50], EntityPixelmon['Dwebble'/517560, l='MpServer', x=13.50, y=63.00, z=196.50], EntityPixelmon['Golett'/517191, l='MpServer', x=-17.50, y=37.00, z=355.50], EntityPixelmon['Dewgong'/516933, l='MpServer', x=-137.28, y=65.00, z=369.25], EntityPixelmon['Dewgong'/516932, l='MpServer', x=-134.81, y=65.00, z=366.78], EntityPixelmon['Swinub'/517186, l='MpServer', x=-143.72, y=64.97, z=372.63], EntityPixelmon['Swinub'/517185, l='MpServer', x=-149.50, y=65.00, z=369.50], EntityPixelmon['Seel'/517070, l='MpServer', x=-117.50, y=63.00, z=278.50], EntityPixelmon['Seel'/517069, l='MpServer', x=-113.49, y=63.39, z=278.30], EntityPixelmon['Swinub'/517194, l='MpServer', x=-94.50, y=68.00, z=256.50], EntityPixelmon['Swinub'/517193, l='MpServer', x=-94.50, y=68.00, z=254.50], NPCTutor['Steve'/514504, l='MpServer', x=-79.53, y=65.00, z=280.47], EntityPixelmon['Larvitar'/516307, l='MpServer', x=-100.50, y=12.00, z=264.50], EntityPixelmon['Swinub'/517214, l='MpServer', x=-132.03, y=66.93, z=275.86], EntityPixelmon['Swinub'/515421, l='MpServer', x=-60.53, y=65.00, z=264.78], NPCTrainer['2'/516573, l='MpServer', x=-57.28, y=63.00, z=200.69], EntityPixelmon['Swinub'/515419, l='MpServer', x=-64.24, y=65.00, z=279.45], EntityPixelmon['Swinub'/517210, l='MpServer', x=-135.50, y=67.14, z=280.22], EntityPixelmon['Roggenrola'/517466, l='MpServer', x=-17.50, y=30.97, z=357.50], EntityPixelmon['Seel'/516441, l='MpServer', x=-95.30, y=64.00, z=233.19], EntityPixelmon['Dewgong'/517209, l='MpServer', x=-60.09, y=65.00, z=247.53], EntityPixelmon['Geodude'/516965, l='MpServer', x=-65.50, y=16.00, z=354.50], NPCTrainer['12'/516708, l='MpServer', x=-148.50, y=64.50, z=214.50], EntityPixelmon['Piloswine'/517220, l='MpServer', x=-100.94, y=69.00, z=259.81], EntityPixelmon['Swinub'/517218, l='MpServer', x=-113.50, y=63.41, z=268.97], EntityPixelmon['Swinub'/517216, l='MpServer', x=-102.72, y=70.00, z=271.97], EntityPixelmon['Seel'/516975, l='MpServer', x=-106.50, y=66.00, z=350.50], EntityPixelmon['Clefairy'/517356, l='MpServer', x=6.50, y=29.97, z=278.50], EntityPixelmon['Dewgong'/516841, l='MpServer', x=-148.50, y=66.00, z=331.50], EntityPixelmon['Seel'/517111, l='MpServer', x=-130.03, y=65.50, z=261.50], EntityPixelmon['Swinub'/517110, l='MpServer', x=-127.41, y=67.00, z=259.44], EntityPixelmon['Sableye'/517238, l='MpServer', x=-39.50, y=10.97, z=346.50], EntityPixelmon['Swinub'/516465, l='MpServer', x=-102.66, y=69.50, z=286.38], EntityPixelmon['Seel'/516351, l='MpServer', x=-77.34, y=65.00, z=269.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1078418720 bytes (1028 MB) / 3174563840 bytes (3027 MB) up to 4131389440 bytes (3940 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4431m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJA	backpacks16840{3.1.0} [Backpacks!] (zz-backpacks 1.8.9 - 3.1.0.jar) 
	UCHIJA	cei{0.1} [Chunk Edge Indicator] (1.8.9-chunkedgeindicator-1.0.jar) 
	UCHIJA	fenceoverhaul{1.2} [Fence Overhaul] ([1.8.x]FenceOverhaul-1.2.jar) 
	UCHIJA	ArchitectureCraft{1.4.1} [ArchitectureCraft] (ArchitectureCraft-1.4.1-mc1.8.9.jar) 
	UCHIJA	AutoSapling{1.0} [Auto Sapling] (AutoSapling 1.2 MC1.8.9.jar) 
	UCHIJA	BiblioCraft{2.0.0} [BiblioCraft] (BiblioCraft[v2.0.0][MC1.8.9].jar) 
	UCHIJA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.2004-universal.jar) 
	UCHIJA	ImmersiveEngineering{0.8-28} [Immersive Engineering] (ImmersiveEngineering-0.8-28.jar) 
	UCHIJA	JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
	UCHIJA	blockdrops{1.0.0} [Block Drops] (Block Drops-1.8.9-1.0.0.jar) 
	UCHIJA	buildingbrickscompatvanilla{1.8.9-1.4.4} [Building Bricks Vanilla Compat] (BuildingBricks-1.8.9-1.4.4.jar) 
	UCHIJA	buildingbricks{1.8.9-1.4.4} [Building Bricks] (BuildingBricks-1.8.9-1.4.4.jar) 
	UCHIJA	Chameleon{1.8.9-1.1.4} [Chameleon] (Chameleon-1.8.9-1.1.4.jar) 
	UCHIJA	chiselsandbits{8.12} [Chisels & Bits] (chiselsandbits-8.12.jar) 
	UCHIJA	ExtraBitManipulation{1.8.9-2.1.1} [Extra Bit Manipulation] (ExtraBitManipulation-1.8.9-2.1.1.jar) 
	UCHIJA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJA	flatcoloredblocks{mc1.8.9-v1.8} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.8.jar) 
	UCHIJA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJA	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCHIJA	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCHIJA	hgp{Release} [Horizontal Glass Panes] (hgp-1.8.9-1.0.2.jar) 
	UCHIJA	hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar) 
	UCHIJA	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCHIJA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJA	journeymap{1.8.9-5.2.4} [JourneyMap] (journeymap-1.8.9-5.2.4-unlimited.jar) 
	UCHIJA	jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.23.jar) 
	UCHIJA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJA	LaserLevel{2.0.0.9} [Laser Level] (LaserLevel-1.8.9-2.0.0.9-universal.jar) 
	UCHIJA	llor{1.0.7-mc1.8.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.7-mc1.8.9.jar) 
	UCHIJA	malisiscore{1.8.9-2.1.6} [MalisisCore] (malisiscore-1.8.9-2.1.6.jar) 
	UCHIJA	malisisdoors{1.8.9-3.1.4} [MalisisDoors] (malisisdoors-1.8.9-3.1.4.jar) 
	UCHIJA	pixelmon{4.3.0-beta4} [Pixelmon] (Pixelmon-1.8.9-4.3.0-beta4-universal.jar) 
	UCHIJA	ShetiPhianCore{3.1.2} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.1.2.jar) 
	UCHIJA	platforms{1.0.4} [Platforms] (platforms-1.8.9-1.0.4.jar) 
	UCHIJA	Schematica{1.7.7.143} [Schematica] (Schematica-1.8.9-1.7.7.143-universal.jar) 
	UCHIJA	SimpleGraves{1.8.9-1.0.0-6} [SimpleGraves] (SimpleGraves-1.8.9-1.0.0-6.jar) 
	UCHIJA	StorageDrawers{1.8.9-2.7.0} [Storage Drawers] (StorageDrawers-1.8.9-2.7.0.jar) 
	UCHIJA	VeinMiner{0.34.1_1.8.9-9901a41} [Vein Miner] (VeinMiner-0.34.1-1.8.9r552+9901a41.jar) 
	UCHIJA	VeinMinerModSupport{0.34.1_1.8.9-9901a41} [Mod Support] (VeinMiner-0.34.1-1.8.9r552+9901a41.jar) 
	UCHIJA	wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
	UCHIJA	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.3-mf-1.8.9-11.15.1.1855.jar) 
	Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
BCModPlugin (zz-backpacks 1.8.9 - 3.1.0.jar)
  brad16840.common.asm.ClassTransformer
Java8CheckerCoremod (Pixelmon-1.8.9-4.3.0-beta4-universal.jar)
  
MalisisCorePlugin (malisiscore-1.8.9-2.1.6.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13440 Compatibility Profile Context 16.200.1013.0' Renderer: 'AMD Radeon R7 200 Series'
	Launched Version: forge-11.15.1.1902
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R7 200 Series GL version 4.5.13440 Compatibility Profile Context 16.200.1013.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor `

**Comment by Nuchaz** [comment]
I'm looking into this. I've had this crash a couple of times myself now, but haven't quite pinned down the cause and how to fix yet.

**Comment by Nuchaz** [comment]
I am pretty confident I have gotten this fixed and will release a version very soon with the fix in it.
