### ISSUE TITLE
crash with spongeforge

### ISSUE THREAD

**Issue by hunter688** [Nuchaz/BiblioCraft#382]
See: https://github.com/SpongePowered/SpongeForge/issues/820

**Comment by Nuchaz** [comment]
I'll see about fixing this. Looks like it is just something new in 1.8+ I was unaware of.

**Comment by Nuchaz** [comment]
I have a fix in for this in the next version I am going to release very soon.

**Comment by hunter688** [comment]
Thanks a lot!
