### ISSUE TITLE
BiblioWoods Forestry recognises no slabs rendering most receipes uncraftable

### ISSUE THREAD

**Issue by AlHollandiyah** [Nuchaz/BiblioCraft#383]
As the title says, BiblioWoods Forestry edition recognises no slabs. This means any receipe using slabs (and thats a lot of them) is rendered uncraftable.

**I am using:**
- Minecraft v1.7.10
- BiblioCraft v1.11.5
- BiblioWoods Forestry v1.7
- Forestry v4.2.15.63

I am unsure whether it is related to the slabs not recognised bug, but I also noticed about half of the fancy signs have the wrong texture (screenshot) which is what let me to research what went wrong in the first place. It only happens with BiblioWoods Forestry, the other receipes / fancy signs are all fine.

![2016-08-14_22 40 29](https://cloud.githubusercontent.com/assets/9619351/17652001/8f506968-6272-11e6-85ca-ebfa2a690c50.png)

**Comment by McBossKiller** [comment]
Did you see if this was a texture pack issue?

**Comment by AlHollandiyah** [comment]
I do use a texture pack (faithful32) so I tried that, but with 'vanilla' textures for the mod it still does the same, so I don't think it's a TP issue!
