### ISSUE TITLE
Armor Stand doesn't render Leather Armor overlay textures

### ISSUE THREAD

**Issue by EzerArch** [Nuchaz/BiblioCraft#384]
The armor stand doesn't render the Leather Armor overlay textures (`leather_layer_X_overlay.png`) on the torso, arms and feet parts.

![2016-08-28_02 12 05](https://cloud.githubusercontent.com/assets/6743303/18031763/19f9385e-6cc5-11e6-9072-4ed37e157c23.png)

Then I have to copy the pixels from Leather Armor overlay textures to the Leather Armor main textures (`leather_layer_X.png`) to avoid those "holes" but I end up "dyeing" unwanted parts.

![2016-08-28_02 11 15](https://cloud.githubusercontent.com/assets/6743303/18031764/1f64b2fa-6cc5-11e6-8247-caaef7f54e1b.png)

Using BiblioCraft[v1.11.5][MC1.7.10] with OptiFine_1.7.10_HD_U_D6.

(Please, don't pay attention to the green guy. He is from... umm, another world. :) )

**Comment by Nuchaz** [comment]
This hopefully shouldn't be an issue in the newer versions for newer version of MC.
