### ISSUE TITLE
Bibliocraft 1.8.9 vers 2.0.1 and 2.00 crashes Minecraft.

### ISSUE THREAD

**Issue by Triliton** [Nuchaz/BiblioCraft#392]
Hello.

I run a little mod pack where i use Conquest Reforge mod.
I run it on MC 1.8.9, with Forge 1720, optifine 1.8.9.HD.U.H2
I have customnpc mod, more creatures, bibliowoods, autosapling, mineblade battlegear, and backpack mod. Also voxelmap/matmos and presence footsteps litemods.
Everything is fine until i add in Bibliocraft, either vers 2.01, or 2.00.
What happens is that after some minutes in the game, the game freezes and then crashes.
The error log seems to adress the shadersmod, but i dont have the shaders on when it crashes.
Ive tried following things:

Changing forge to 1722. Same issue happened.
Changing Optifine. Same issue happened.
Changed both Forge and Optifine together, still same issue.

For me it seems like its not rendering well with either biomes o plenty, or another mod.

Whats also is strange, is that i need to set connected textures back from fancy to none, to fast in order
to get the connected textures from Conquest reforge mod to work.
So there is something there.

Heres the crash report: http://pastebin.com/FY1cS7dd

How can i fix this?

**Comment by Triliton** [comment]
@Nuchaz any idea??

**Comment by Nuchaz** [comment]
Unrelated to BiblioCraft, something to do with something called a BattlemodeHook, whatever mod that is from.
