### ISSUE TITLE
TiCon Tools and Item Display

### ISSUE THREAD

**Issue by Zsashas** [Nuchaz/BiblioCraft#394]
It seems that Tinkers tools don't like being displayed in Bibliocraft racks. Item Shelf displays two of the tool, crossing each other, and the Tool Rack has the tool lodged in it perpendicular to what it should be.

Tested so far with Dark Oak item shelf and tool rack, with a TiCon shovel and lumberaxe.

![2017-01-12_06 25 54](https://cloud.githubusercontent.com/assets/6917535/21893538/3cb631bc-d890-11e6-9161-b9d3958f71d6.png)
![2017-01-12_06 26 01](https://cloud.githubusercontent.com/assets/6917535/21893537/3cb61592-d890-11e6-8843-2755d0f0068c.png)

**Comment by Ravin890** [comment]
Bibliocraft never liked how tinker tools rendered and did that all the time

**Comment by Nuchaz** [comment]
Support for tinkers tools and weapons is improving in the next releases for 1.10.2 and 1.11.2.
