### ISSUE TITLE
crash after updating from 1.8.2 to 2.0.1

### ISSUE THREAD

**Issue by teddylovecake** [Nuchaz/BiblioCraft#398]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 1/26/17 4:03 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at jds.bibliocraft.models.BiblioModelColor.func_177550_a(BiblioModelColor.java:159)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:88)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_178258_b(ForgeBlockModelRenderer.java:53)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:40)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:30)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
	at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:704)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:194)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at jds.bibliocraft.models.BiblioModelColor.func_177550_a(BiblioModelColor.java:159)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:88)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_178258_b(ForgeBlockModelRenderer.java:53)

-- Block model being tesselated --
Details:
	Block: bibliocraft:LampGold[color=white]
	Block location: World: (-1051,58,176), Chunk: (at 5,3,0 in -66,11; contains blocks -1056,0,176 to -1041,255,191), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:40)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:30)

-- Block being tesselated --
Details:
	Block type: ID #207 (tile.BiblioCraft:LampGold // jds.bibliocraft.blocks.BlockLampGold)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-1051,58,176), Chunk: (at 5,3,0 in -66,11; contains blocks -1056,0,176 to -1041,255,191), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
	at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:704)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['teddy_love_cake'/15, l='MpServer', x=-1010.11, y=67.00, z=275.69]]
	Chunk stats: MultiplayerChunkCache: 961, 961
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -1167.00,60.00,164.00 - World: (-1167,60,164), Chunk: (at 1,3,4 in -73,10; contains blocks -1168,0,160 to -1153,255,175), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Level time: 14639165 game time, 7172934 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 52 total; [EntityPixelmon['Natu'/517, l='MpServer', x=-930.28, y=66.97, z=246.59], EntityPixelmon['Natu'/518, l='MpServer', x=-934.50, y=66.97, z=247.50], EntityPixelmon['Natu'/519, l='MpServer', x=-938.64, y=67.85, z=248.44], EntityPixelmon['Carvanha'/1035, l='MpServer', x=-1109.19, y=48.90, z=238.23], EntityBat['Bat'/14, l='MpServer', x=-947.64, y=59.88, z=285.77], EntityPlayerSP['teddy_love_cake'/15, l='MpServer', x=-1010.11, y=67.00, z=275.69], EntityPixelmon['Magikarp'/39, l='MpServer', x=-1062.74, y=55.36, z=349.24], EntityPixelmon['Magikarp'/40, l='MpServer', x=-1102.28, y=55.44, z=327.31], EntityPixelmon['Magikarp'/41, l='MpServer', x=-1107.14, y=55.47, z=342.42], EntityPixelmon['Magikarp'/42, l='MpServer', x=-1062.30, y=55.37, z=339.33], EntityPixelmon['Magikarp'/43, l='MpServer', x=-1093.94, y=55.51, z=250.33], EntityPixelmon['Magikarp'/45, l='MpServer', x=-1092.10, y=55.41, z=282.34], EntityPixelmon['Xatu'/432, l='MpServer', x=-921.16, y=77.50, z=343.28], EntityPixelmon['Goldeen'/436, l='MpServer', x=-1089.47, y=51.18, z=278.31], EntityPixelmon['Goldeen'/437, l='MpServer', x=-1106.39, y=51.00, z=331.61], EntityPixelmon['Magikarp'/441, l='MpServer', x=-1051.01, y=54.41, z=262.99], EntityPixelmon['Magikarp'/442, l='MpServer', x=-1055.50, y=54.41, z=313.45], EntityPixelmon['Magikarp'/443, l='MpServer', x=-1073.92, y=54.38, z=336.90], EntityPixelmon['Magikarp'/444, l='MpServer', x=-1080.76, y=52.69, z=266.21], NPCTrainer['5'/580, l='MpServer', x=-1091.69, y=59.97, z=178.03], EntityPixelmon['Venipede'/461, l='MpServer', x=-1057.50, y=66.97, z=249.50], EntityPixelmon['Scolipede'/462, l='MpServer', x=-918.50, y=60.00, z=265.50], EntityPixelmon['Venonat'/464, l='MpServer', x=-998.50, y=57.97, z=307.50], EntityPixelmon['Venipede'/470, l='MpServer', x=-941.50, y=67.00, z=277.47], EntityPixelmon['Venonat'/471, l='MpServer', x=-1075.41, y=59.97, z=194.38], EntityPixelmon['Natu'/472, l='MpServer', x=-913.29, y=59.94, z=226.85], EntityPixelmon['Venipede'/473, l='MpServer', x=-1049.50, y=66.97, z=275.50], EntityPixelmon['Slakoth'/474, l='MpServer', x=-1036.50, y=56.97, z=340.50], EntityPixelmon['Venomoth'/475, l='MpServer', x=-951.50, y=67.00, z=248.50], EntityPixelmon['Whirlipede'/476, l='MpServer', x=-1033.72, y=59.97, z=179.88], EntityPixelmon['Pinsir'/477, l='MpServer', x=-1020.84, y=59.00, z=363.63], EntityPixelmon['Natu'/478, l='MpServer', x=-956.53, y=55.94, z=348.84], EntityPixelmon['Venipede'/480, l='MpServer', x=-1019.38, y=59.97, z=217.50], EntityPixelmon['Pinsir'/483, l='MpServer', x=-1055.69, y=59.97, z=189.59], EntityPixelmon['Natu'/484, l='MpServer', x=-1012.99, y=56.19, z=332.37], EntityPixelmon['Magikarp'/1252, l='MpServer', x=-1060.37, y=55.84, z=301.05], EntityPixelmon['Magikarp'/1253, l='MpServer', x=-1069.33, y=57.11, z=305.27], EntityPixelmon['Venomoth'/486, l='MpServer', x=-912.22, y=60.00, z=272.06], EntityPixelmon['Magikarp'/1254, l='MpServer', x=-1069.44, y=55.67, z=306.86], EntityPixelmon['Venomoth'/487, l='MpServer', x=-918.03, y=60.00, z=274.53], EntityPixelmon['Magikarp'/1255, l='MpServer', x=-1071.10, y=56.53, z=306.84], EntityPixelmon['Venipede'/488, l='MpServer', x=-993.81, y=58.92, z=194.50], EntityPixelmon['Magikarp'/1256, l='MpServer', x=-1068.98, y=54.00, z=303.81], EntityPixelmon['Venonat'/489, l='MpServer', x=-1044.50, y=64.97, z=308.50], EntityPixelmon['Magikarp'/1257, l='MpServer', x=-1078.49, y=55.97, z=305.61], EntityPixelmon['Magikarp'/1258, l='MpServer', x=-1070.87, y=58.97, z=305.34], EntityPixelmon['Magikarp'/1259, l='MpServer', x=-1063.78, y=58.12, z=304.69], EntityPixelmon['Venonat'/493, l='MpServer', x=-1011.40, y=56.59, z=332.62], EntityPixelmon['Venomoth'/495, l='MpServer', x=-956.84, y=67.00, z=264.75], EntityPixelmon['Venomoth'/496, l='MpServer', x=-960.13, y=67.00, z=256.97], EntityPixelmon['Venomoth'/497, l='MpServer', x=-952.13, y=67.00, z=264.84], EntityPixelmon['Venomoth'/498, l='MpServer', x=-953.50, y=67.00, z=259.06]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 452736512 bytes (431 MB) / 1929379840 bytes (1840 MB) up to 1929379840 bytes (1840 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	IntCache: cache: 1, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	ArchitectureCraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.8.9.jar) 
	UCHIJAAAA	BiblioCraft{2.0.1} [BiblioCraft] (BiblioCraft[v2.0.1][MC1.8.9].jar) 
	UCHIJAAAA	cfm{4.0.1} [MrCrayfish's Furniture Mod] (cfm-4.0.1-mc1.8.9.jar) 
	UCHIJAAAA	customnpcs{1.8.9} [CustomNPCs] (CustomNpcs_1.8.9(29oct16).jar) 
	UCHIJAAAA	JoypadSplitscreenMod{1.8.9-0.22} [Joypad / SplitScreen Mod] (JoypadMod-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	pixelmon{4.3.1} [Pixelmon] (Pixelmon-1.8.9-4.3.1-universal.jar) 
	UCHIJAAAA	pixelextras{2.1.7} [Pixel Extras] (PixelExtras-1.8.9-2.1.7-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1902-1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Pixelmon SS Beta Ver .01.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz

**Comment by Nuchaz** [comment]
Sorry, it is not possible to load a world with bibliocraft from minecraft 1.7.10 or earlier into minecraft 1.8.9 or later. I had to rebuild the mod from the ground up and so much changed it is no longer compatible. That is why I changed the version of BiblioCraft from 1.x.x to 2.x.x.

**Comment by teddylovecake** [comment]
Thats what i was guessing iv had to do this multiple times, are you currently upgrading a version for 1.10.2?

**Comment by Nuchaz** [comment]
I released a version for 1.10.2 last weekend ;)
