### ISSUE TITLE
[1.10.2] Desk Bell... bug? Hahaha

### ISSUE THREAD

**Issue by CelticChristoph** [Nuchaz/BiblioCraft#401]
MC: 1.10.2 / Forge: 12.18.3.2221
Bibliocraft v2.2.0

When I right-click my desk bell, it plays one of the "cave ambiance" sounds. You know, the spooky whoosh sounds it plays from time to time when you're wandering around?

Pretty funny, but would definitely love to see it fixed. xD

**Comment by Nuchaz** [comment]
That is interesting. Is this in singleplayer or on a server? I guess I hadn't really tested the bell on a server, but I didn't have no issue in singleplayer. I will look into this.

**Comment by CelticChristoph** [comment]
Was on a dedicated server!

**Comment by Cobra1117** [comment]
This also happens when open/closing display cases.

**Comment by Nuchaz** [comment]
This is fixed in v2.1.1 for MC 1.9.4 and v2.2.1 for MC 1.10.2 which I am about to release. The issue was I hadn't properly registered my sounds so none of them worked on a server. The procedure for doing so had changed in v1.9,x and newer.
