### ISSUE TITLE
[1.10.2] When looking at @bibliocraft in inventory with JEI, FPS takes a major hit.

### ISSUE THREAD

**Issue by CelticChristoph** [Nuchaz/BiblioCraft#402]
MC: 1.10.2 / Forge: 12.18.3.2221
Bibliocraft v2.2.0

When using Bibliocraft, if I look up @bibliocraft in JEI, my framerate goes from my locked 145FPS to around 7-10FPS.

I'm unsure what causes this, but I'm assuming it has something to do with the rendering method or calls made when viewing the item model in inventory. I can continue testing if you'd like, if there's any questions you have. Lemme know!

Thanks,
Celtic

**Comment by UnPure** [comment]
I can confirm this, right when searching for bibliocraft stuff my FPS drop from solid 120 to 6.
For me the items also are all named "Tooltip error, see log".

**Comment by JaSpr** [comment]
OMG can confirm.  Wow.

**Comment by JaSpr** [comment]
Was this issue resolved??

**Comment by Nuchaz** [comment]
yeah, in BiblioCraft v2.2.1. I forgot to close this issue when I released that version.
