### ISSUE TITLE
Lower framerate while viewing items/blocks with vanilla/JEI menus(1.10.2)

### ISSUE THREAD

**Issue by Nuinethir** [Nuchaz/BiblioCraft#403]
**Issue:**
I am getting a framerate issue when I view blocks/items through the vanilla creative menu as well as JEI's menu. This doesn't happen with any other mods.

**Steps to reproduce:**
- When I search for mod-specific items in JEI using @bibliocraft, framerate dives.
- Searching subsets of Bibliocraft lead one of the culprits (?) seeming to be the typewriters.
- Turning off shaders/Optifine didn't help.
   - Optifine & shaders on: 40 fps --> 4 fps
   - Optifine & Shaders off: 60 fps --> 7 fps
- Placing one of each color typewriter on the ground lowered framerate by only 10-12 fps instead of the drastic numbers above. 

**Running:**
Minecraft Forge 12.18.3.2122
BiblioCraft v2.2.0 for 1.10.2
OptiFine_1.10.2_HD_U_D4
KUDA-Shaders v.6.2.81

**CPU:**
Windows 7 Pro 64-bit SP1
i5-4670 3.4GHz
16GB DDR3-1600 (5GB dedicated to Minecraft)
250GB SSD
GTX 970 @ 2560 x 1080

-----------------------------------------------------------------

*edit* - I tried disabling typewriters in the config and reloaded Minecraft. Framerate is not as bad, but still very noticeable. Again, this is only when viewing Bibliocraft items, either through the vanilla menu or JEI's menu.

**Comment by CelticChristoph** [comment]
Way more information than my post, but appears to be the same issue as #402.

**Comment by Nuchaz** [comment]
Yeah, this has to do with item rendering. I experience the same issue too. I need to build a caching system to try to address this. I made a note of this as a high priority issue when I get some time. I have some ideas on how to make it work, just might require a little time.

**Comment by Nuchaz** [comment]
I already started making progress on this and have some real promising results. Hopefully, if time permits, I will try to finish applying my new cache system to rest of the models and try to get a release out this coming weekend.

**Comment by CelticChristoph** [comment]
You da best. Thanks for your efforts! :heart:

**Comment by Nuchaz** [comment]
This should be fixed in v2.1.1 for MC 1.9.4 and v2.2.1 for MC 1.10.2 which I am about to release real soon.
