### ISSUE TITLE
BUG crafting from Recipe Books

### ISSUE THREAD

**Issue by HeberonYT** [Nuchaz/BiblioCraft#405]
The Config option to disable crafting from Recipe Books it does not work, I have disabled it from the server but you can still place the book and save the recipes, of course it also throws the crafted object.

Mod Version: `BiblioCraft[v1.11.5][MC1.7.10].jar`

**Comment by Nuchaz** [comment]
I'll look into this when I get some time.

**Comment by Nuchaz** [comment]
I'll have this fixed in the next release. I plan to put out one last release for 1.7.10 with a few bug fixes in addition to an updated 1.10.2 version and a 1.11.2 version.
