### ISSUE TITLE
Grandfather Clock crash!

### ISSUE THREAD

**Issue by BritishMindslave** [Nuchaz/BiblioCraft#407]
Today I placed a grandfather clock on top of a vanilla bookshelf and it caused a crash that refuses to let me load up the world!
I attached the crashlog, I don't think it has to do with compatibility. ouo;
[crash-2017-02-06_12.05.19-client.txt](https://github.com/Nuchaz/BiblioCraft/files/755340/crash-2017-02-06_12.05.19-client.txt)

**Comment by Nuchaz** [comment]
This looks related to the same issue as #404

**Comment by Nuchaz** [comment]
closing this to consolidate to the other report. Still working on the issue.
