### ISSUE TITLE
[1.10.2-2.2.1]  3 warning in console

### ISSUE THREAD

**Issue by comdarksider** [Nuchaz/BiblioCraft#408]
Please fix warning in console of server.  I use BiblioCraft[v2.2.1][MC1.10.2].

Detail warning  : 
1.  mod id.  input your mod id of bibliocraft.
2.  Dangerous alternative prefix `minecraft` for name `ReadingEnchantment.  
3.  Unknown recipe class!  Fix recipe class

Link errors :
1.  In github  - https://gist.github.com/comdarksider/e7e0d0af8eef047bc3272a3a6e7587ea
2.  In pastebin  - http://pastebin.com/mxKGJvYa

Thank you very much for working.

**Comment by Nuchaz** [comment]
I'll try to fix some of these.

**Comment by Nuchaz** [comment]
These will be fixed in the next release for MC 1.10.2. The mod id will be lowercase in the version for v1.11.2.
