### ISSUE TITLE
Rendering Related Stuff

### ISSUE THREAD

**Issue by Ravin890** [Nuchaz/BiblioCraft#409]
The placeholder icon for the marker pole is kinda invading the guy to the left's territory.
![2017-02-06_14 55 04](https://cloud.githubusercontent.com/assets/13302573/22765337/a2467754-ee3d-11e6-99c2-2cfe06988254.png)

Also if you use a tape measure on any block which isn't a full block (bookcase, potion shelf, ect.) it turns from its original orientation until you update it somehow.

Also you can see the wall through the top of the framed chests if you have it right by the wall. (This one is more of how you made chest compared to vanilla chest)

**Comment by Nuchaz** [comment]
I'll look into this stuff. Your actually never supposed to have the marker pole in your inventory, but it definitely should update itself for correct orientation.

**Comment by Ravin890** [comment]
lol well its more of seeing it in JEI as opposed to (an img of that would be a little bit more cluttered so i decided to put it in my inventory to make it more clear) :D

**Comment by Nuchaz** [comment]
I'll have this fixed in the next release, coming soon.
