### ISSUE TITLE
1.10.2 Moded Server Crash 

### ISSUE THREAD

**Issue by wlam02** [Nuchaz/BiblioCraft#411]
[crash-2017-02-15_18.55.56-client.txt](https://github.com/Nuchaz/BiblioCraft/files/778802/crash-2017-02-15_18.55.56-client.txt)

**Comment by Nuchaz** [comment]
This looks like it might be the same issue as #404

**Comment by Nuchaz** [comment]
Closing to consolidate. Still working on issue.
