### ISSUE TITLE
[1.10.2] Armor Stand Bugs

### ISSUE THREAD

**Issue by Xiaminou** [Nuchaz/BiblioCraft#412]
1. Armor Stand does not render armor properly:

![2017-02-16_18 09 36](https://cloud.githubusercontent.com/assets/8670392/23032009/58e46d0a-f473-11e6-9333-e0d8188e087a.png)

2. Cannot shift+click armor into armor stand.
3. When inserting armor into armor stand via pipes slots are not restricted to armor parts resulting in this:

![2017-02-16_18 10 30](https://cloud.githubusercontent.com/assets/8670392/23032073/9792def6-f473-11e6-87c5-4bfa25ae419f.png)

4. Breaking the upper part of an Armor Stand returns an Oak Armor Stand instead of the correct one.

Minecraft: 1.10.2
Forge: 2185
Bibliocraft: 2.2.1
Mods: [list.txt](https://github.com/Nuchaz/BiblioCraft/files/780924/list.txt)

**Comment by Nuchaz** [comment]
hmm, interesting. I'll look into this. I ran into another mod, LLibrary that seems to break armor stand rendering for whatever reason. I don't see that in your mod list, but I wonder if it is related to another mod, perhaps a core mod of some sort.

**Comment by Xiaminou** [comment]
Yeah, you're right, it doesn't happen with Bibliocraft alone. Definitely a mod compatibility issue.

**Comment by mcdodge34** [comment]
Got a strange issue that started happening today in my FTB Beyond world, my 2 spruce armor stands begin to act weirdly, they duped themselves to oak armor stands and they turned sideways by themselves, I started playing with Rftools builder perhaps its got something to do with this, or the Rftools elevator that are near the armor stands...

**Comment by FiniteParadox22** [comment]
I have the same issue as mccdodge but instead of Rftools elevator I am using the elevator mod (ports in open blocks' elevator to 1.10.2) and I am on a modified version of ATlauncher MechMagic. I wonder if it has to do with the elevators somehow.

**Comment by Nuchaz** [comment]
I think I got all but one of the issues mentioned here sorted. The only thing left is the sorting when coming from pipes or hoppers. The way that is done seems to have changed and I think it involved a new thing called capabilities. I plan to do some more research and figure that one out soon, likely after the next release.
