### ISSUE TITLE
Texture Rendering Issue

### ISSUE THREAD

**Issue by RobertLSnead** [Nuchaz/BiblioCraft#413]
Textures not rendering correctly and causing non texture rendering near various biblio objects.
Also this appears to be random, it is fine one minute and not the other.
This mod is the only one affected with this issue.
Resource pack does not affect this rendering issue.

MC 1.10.2
Forge 12.18.2.2185
BiblioCraft [v2.2.1][MC1.10.2]

-Snap Shot:
![image](https://cloud.githubusercontent.com/assets/5366796/23086168/874bac78-f539-11e6-8687-27eb0a1bc6c2.png)

**Comment by gdude2002** [comment]
We're having some rendering issues on MC 1.10.2 as well, Forge 12.18.2.2221

<details> 
  <summary>Screenshots</summary>

![](http://i.imgur.com/wLVjaFm.png)

![](http://i.imgur.com/1PwApXN.png)

![](http://i.imgur.com/N3Et3QB.png)
</details>

**Comment by Ravin890** [comment]
maybe posting log can help

**Comment by gdude2002** [comment]
I'll grab one next time that happens

**Comment by Techokami** [comment]
I'm having this problem as well, and it is very sporatic.
![2017-02-21_20 13 31](https://cloud.githubusercontent.com/assets/1530728/23192919/1af67e98-f874-11e6-9f30-7a6241abf650.png)
Disc racks were rendering like this as well, but the "model" was offset one block to the south and one block to the west. A few weeks ago, I was having a similar issue with desks and stools, and the stools were offset to the south-west. Reloading the client does "solve" the problem, but I think something more permanent needs to be investigated.

I tried to look through my logs for anything of note, and I did not see anything involving Bibliocraft, aside from some load time warnings about missing item JSON? But it falls back to the actual world model for that. There were also a bunch of NullPointerExceptions from JourneyMap, trying to map out areas that had these broken models, but nothing actually went back into Bibliocraft that could be used for tracing.

**Comment by Nuchaz** [comment]
I am working on investigating this issue. I just had to happen today. This seems related to #418

**Comment by gdude2002** [comment]
Yeah, I noticed that as well, forgot to mention it. Should be related.

**Comment by Nuchaz** [comment]
Closing this to consolidate the issue to one thread. I am pretty sure i have a good idea what is happening now and should have a fix in place for the next release.
