### ISSUE TITLE
[1.10.2] Fancy Sign colored text is not the right color

### ISSUE THREAD

**Issue by Xiaminou** [Nuchaz/BiblioCraft#416]
![2017-02-22_16 46 56](https://cloud.githubusercontent.com/assets/8670392/23219172/ab841ef2-f91e-11e6-93af-96ce276b07be.png)
![2017-02-22_16 46 58](https://cloud.githubusercontent.com/assets/8670392/23219173/ab84bfb0-f91e-11e6-8a61-1ca4335c1356.png)
![2017-02-22_16 51 46](https://cloud.githubusercontent.com/assets/8670392/23219690/0c8e7cbe-f920-11e6-96df-af345f8d99cd.png)

**Comment by Nuchaz** [comment]
This is an issue that started in 1.8.9 after the rendering changes and I haven't figured this one out quiet yet. I'll look into it better when I get some time.

**Comment by Nuchaz** [comment]
I finally figured this one out after studying the vanilla sign. This will be fixed in the next release for 1.10.2 and newer. (coming soon)
