### ISSUE TITLE
[1.10.2] Tesselating block model

### ISSUE THREAD

**Issue by YOYOK9** [Nuchaz/BiblioCraft#419]
I've noticed that sometimes when I walk around my base and either look directly at or in the general direction of a bibliocraft block I will crash. Or sometimes will just crash without being near it. 

Report: http://pastebin.com/YssaxtyD
Versions: 
Biblio: BiblioCraft[v2.2.1][MC1.10.2]
Forge: 1.10.2-12.18.3.2221

**Comment by YOYOK9** [comment]
have also noticed that when a Player logs back in after crashing and try to teleport or even move somewhere they do a "warp" back and forth from where they tried to go to and back to where they first crashed. Also the player seem to "fake Die" when they crash. But log in with all their stuff still. (keep inv isn't enabled)

**Comment by Ravin890** [comment]
Is there a bookcase near your location prior to crash?

**Comment by YOYOK9** [comment]
Yes there was. Are they what is causing the issues?

**Comment by Ravin890** [comment]
Well I am looking at the crash and see "Block being tesselated" a few times and it is referring to the bookcase from bibliocraft.

**Comment by YOYOK9** [comment]
Ah, I have since removed the bookcase and things seem to be better now.

**Comment by Nuchaz** [comment]
This looks related to the same issue as #404 
I am still working on figureing this out.

**Comment by Nysteri** [comment]
Hi there! Our server is also experiencing this error. Many times, Iron lanterns, Gold lanterns, tables, or a mix of various blocks will decide to display the checkered "Missing block", and/or crash players either as they're attempting to log in, or as they load various other Bibliocraft items.

One of our players is experiencing this to a tremendous degree, and even doing simple World Edit commands (Such as setting a block of grass to a block of stone) have been giving him this error. If it would help get to the bottom of this at all, [here is the crash log he sent me after such an occurence](http://pastebin.com/Fwc1CNU7).

Thanks a lot for all of the work that you do on this mod, and hopefully this issue can get resolved!

**Comment by Seth0067** [comment]
+1 here - For us, I think Optifine is the issue as I can disable that and stuff will work.  Here's one of many crash logs.  [Crash Log](https://pastebin.com/31AGjbkP)

**Comment by Nuchaz** [comment]
I finally got a good understanding of what is happening and I got a fix in place. I am 90% sure this will take care of it. Look for a fix in the next update (coming soon).
