### ISSUE TITLE
[1.7.10] defaultbigbooktextscale

### ISSUE THREAD

**Issue by Fabboz** [Nuchaz/BiblioCraft#420]
The config option in the title only work if i give the book from NEI or with the crative tab, not work if i craft in a workbanch. I very need that fix =) 

thx 

Version 1.11.5

**Comment by Fabboz** [comment]
ok the config work in the second and successives.

**Comment by Nuchaz** [comment]
This should be fixed in the next release for 1.7.10 and newer. (coming soon)
