### ISSUE TITLE
[1.10.2] Clipboard changes two pages at the time.

### ISSUE THREAD

**Issue by Mattsingen** [Nuchaz/BiblioCraft#423]
When a clipboard is placed on a wall and you click the arrows to change page, it moves two pages at the time.
In hand it works correctly and it retains it the current page when put on wall. So this is a minor nuisance and not a critical bug.

The version I use is 2.2.1, in my own modpack.
I haven't tested that the "bug" still is there without any other mods, but hopefully someone can confirm this bug in other packs.

**Comment by Nuchaz** [comment]
This will be fixed in the next release.
