### ISSUE TITLE
Typesetter isn't saving finished books

### ISSUE THREAD

**Issue by Disturbeddragon1** [Nuchaz/BiblioCraft#424]
Even after having removed all mods except for bibliocraft and of course forge, still having issues with the typesetter not actually saving out finished books to the folder that gets created in the .minecraft/config/books_bibliocraft folder, so we have ruled out other mods conflicting as an issue. It will create the folder but then won't go any further. In game it'll show up as blue like it actually saved until you take the book you're trying to save off the typesetter and then reset it. When clicking on the area of the typesetter that shows what books are being managed, it is completely empty.

Here's the versions I'm running, if it helps:
Minecraft 1.10.2 (Survival Single Player world open to LAN)
Bibliocraft V2.2.1 for MC1.10.2
Forge 1.10.2-12.18.3.2185

Let me know if anyone has other questions or need more information that I may have forgotten to add above, and I also apologize if I'm slow in response to this, in the process of moving. n_n

**Comment by Nuchaz** [comment]
I was having an issue properly detective if the game is running on the local server or a dedicated server. This should be fixed in the next release.
