### ISSUE TITLE
[1.10.2] Crash with Shelves and Thermal Expansion auto-input

### ISSUE THREAD

**Issue by b0bst3r** [Nuchaz/BiblioCraft#425]
Crashlog - https://gist.github.com/b0bst3r/1e76530fd9189ae9ba0ef2a2f288afe0

CoFHCore-1.10.2-4.0.2.150-universal
ThermalExpansion-1.10.2-5.0.2.83-universal
ThermalFoundation-1.10.2-2.0.2.76-universal
Forge 2221
Bibliocraft 2.2.1 (crash log says 2.1.1 but re-tested with 2.2.1)

To repeat:

    Place down Energetic infuser.
    Place down 2 Bibliocraft shelves (the ones which have 4 slots and the type you hang on a wall) one each side of the infuser.
    Upgrade the infuser to hardened
    Set left side as input and right side as output on the infuser
    Enable auto input on Infuser GUI and crash occurs

World will not load from that point on unless the infuser is world edited out (or the input side shelf).

Pics
Setup like this - http://i.imgur.com/1JHSu1e.png
As soon as this is enabled - http://i.imgur.com/vmyAvfr.png crash occurs

https://github.com/CoFH/Feedback/issues/64

**Comment by KingLemming** [comment]
This *seems* to happen because we query it for an IItemHandler, which it claims to have, and then hands back a null.

While I realize capabilities are a little ill-defined, Lex has made it pretty clear that this is incorrect behavior.

**Comment by Nuchaz** [comment]
Interesting. I actually haven't implemented IItemHandler. I'm not sure why it would claim to have it. My TE's only extends TileEntity and implement IInventory at this point.. But regardless, IItemHandler looks like something useful that I should implement, so I'll go ahead and add support for that and hopefully it will solve these types of problems.

**Comment by Nuchaz** [comment]
Support added and will be in the next release.
