### ISSUE TITLE
[1.10.2] Config settings for additional items in rack/shelves not honored

### ISSUE THREAD

**Issue by nnystyxx** [Nuchaz/BiblioCraft#426]
Adding new terms to be allowed in the potion shelf, tool rack, etc. doesn't work no matter how I attempt to format the names.

For reference, I'm trying to make a disc rack take cookies, since they are also disk-shaped.

1.10.2, forge 12.18.3.2239, Bibliocraft 2.2.1.

**Comment by Ravin890** [comment]
But there is a cookie jar for those

**Comment by Nuchaz** [comment]
I tried to duplicate this, but it seems to be working fine for me. I added ", cookie" to the disc rack config option and cookies worked, added ", bucket" to the end of the tool rack config options and it worked as well. I'm not sure why it isn't working for you here.
