### ISSUE TITLE
Tool rack deletes itemstacks over 1 quantity.

### ISSUE THREAD

**Issue by Fokson** [Nuchaz/BiblioCraft#430]
Toolrack vs stackable items, such as buckets in Bibliocraft 2.2.0 (2.2.1) for Minecraft 1.10.2, Forge 12.18.3.2221

1> ![Loading...](https://puu.sh/uMpO8/59ea925943.jpg)
2> ![Loading...](http://puu.sh/uMpP9/de18e1bb97.jpg)
3> ![Loading...](http://puu.sh/uMpPG/ab678153a0.jpg)
4> ![Loading...](http://puu.sh/uMpQe/87e9300089.jpg)
5> ![Loading...](http://puu.sh/uMpQQ/ef7292d1e8.jpg)
6> ![Loading...](http://puu.sh/uMpRx/7795505a2d.jpg)

**Comment by Nuchaz** [comment]
Thanks for the detailed report. This will be fixed in the next release.
