### ISSUE TITLE
Clipboard dupe?

### ISSUE THREAD

**Issue by Lethann** [Nuchaz/BiblioCraft#431]
This could be a weird fluke because we had the "Clipboard" mod installed first then replaced it with Bibliocraft.

When i take down a clipboard from the wall I'll occasionally get other clipboards (up to 2) showing in my inventory but in a "sideways" almost invisible position. In hand they are sideways and I'm unable to use them. Can place them on walls but not otherwise interact with them. Thankfully the one clipboard I did actually make seems fine.

**Comment by Nuchaz** [comment]
This will be fixed in the next release. It is droping both the clipboard item and the clipboard block (which shouldn't exist as an item).
