### ISSUE TITLE
[Bug] Framed Shelves do not retain the block they were framed with

### ISSUE THREAD

**Issue by Erinbutt** [Nuchaz/BiblioCraft#436]
Framed shelves do not keep the block they were framed with when broken. Blocks used to frame the shelf also are destroyed when broken.

**Comment by Nuchaz** [comment]
Looks like this is the case for all framed blocks. Looks like the name of the method I used to get that information when the block is broken has changed name and the one I am using is being called too late, after the tile entity with the information is destroyed. This is an easy fix and will be in the next release (coming soon).
