### ISSUE TITLE
[Bug] Furniture panelers causes game to freeze occasinally when broken/replaced, Causes them and shelves to render strangely when game is restarted

### ISSUE THREAD

**Issue by Erinbutt** [Nuchaz/BiblioCraft#437]
Placing Furniture Panelers will occasionally freeze up the game, requiring you to have to force close the game, I don't receive a crash report when it does happen. Has happened with all varieties of panelers, but not all the time. After restarting the game shelves + panelers will sometimes show up with broken models, textures, invisible or as full blocks using whatever material they are made of. Items placed on the shelves are not lost and are still on the shelves. I am using the 1.10.2- 2.2.1 Version of the mod.

![2017-03-26_21 50 51](https://cloud.githubusercontent.com/assets/13043237/24337810/997c2682-126e-11e7-85a1-838d62b2d248.png)

![2017-03-26_21 56 50](https://cloud.githubusercontent.com/assets/13043237/24337949/9d60eaac-126f-11e7-81fd-42bfa74a0737.png)

![2017-03-26_21 57 12](https://cloud.githubusercontent.com/assets/13043237/24337957/a821e63a-126f-11e7-8312-fcddea441fea.png) 
_Difficult to see, but this is one of the shelves placed. I can walk through it and see my items on it._

**Comment by Nuchaz** [comment]
related to #418   Closing this to consolidate. I have a fix planned, I think I know what is going on. Hopefully the next release will take care of it.
