### ISSUE TITLE
[1.10.2] Clipboard dupes

### ISSUE THREAD

**Issue by Speiger** [Nuchaz/BiblioCraft#440]
Placing Bibliocraft Clipboard on wall and breaking it results in a duped item.

Version of BiblioCraft: the one in FTB Beyond

**Comment by Nuchaz** [comment]
This will be fixed in the next release. This is also the case with the marker pole from the clipboard if you break it. It's not duping, but rather with the clipboard, droping both the clipboard item, where all the data is stored, and the clipboard block, which shouldn't exist as an item.
