### ISSUE TITLE
Need to know exact plan recipes for compass needle in BiblioWoodsTFC

### ISSUE THREAD

**Issue by lllMohandarlll** [Nuchaz/BiblioCraft#441]
Hello,
I was tryng to remove the compass needle anvil recipe from TFC BiblioWoods using TFCTweaker (a compatibility addon of minetweaker for terrafirmacraft), but it does not work with your item, even after reloading istance.. could you tell me what is the exact  plan name?

I tryed with mods.Terrafirmacraft.Anvil.removeAnvilRecipe(<BiblioWoodsTFC:item.BiblioTFCItems:21>, <terrafirmacraft:item.Wrought Iron Ingot>, "needle", 3);
and mods.Terrafirmacraft.Anvil.removeAnvilRecipe(<BiblioWoodsTFC:item.BiblioTFCItems:21>, <terrafirmacraft:item.Wrought Iron Ingot>, "waypoint compass needle", 3);
and many others 
but still with no results

**Comment by Nuchaz** [comment]
heres a snippit of code that had all the strings I used for the different anvil plan names:

`		//plumb line - brass ingot + string
		//hand drill = iron ingot
		//desk bell - iron plate
		//chase = iron ingot
		//specticle frames = 1 iron sheet
		// monocle = 1 gold sheet
		//compass base - gold sheet
		//compass needle = iron ingot
		//map tool - 2 iron ingot
		// rollers - 2 iron ingot
		// type facing 1 iron sheet (punch punch punch)
		//lamps and lanterns = 1 double sheet (or single sheet) of appropriot metal
		
		String compassBodyPlan = "compassBody";
		String compassNeedlePlan = "compassNeedle";
		String plumbLinePlan = "plumbLine";
		String handDrillPlan = "handDrill";
		String deskBellPlan = "deskBell";
		String chasePlan = "chase";
		String spectacleFramesPlan = "spectacleFrames";
		String monocleFramePlan = "monocleFrame";
		String typefacingPlan = "typefacing";
		String rollersPlan = "rollers";
		String mapToolPlan = "mapTool";
		
		String lamplan = "lamp";
		String lanternPlan = "lantern";`

Hopefully that helps.
