### ISSUE TITLE
Crash with Optifine

### ISSUE THREAD

**Issue by NillerUdenDild** [Nuchaz/BiblioCraft#445]
Hey!

I wasn't sure where to post this crashlog to be honest, as it's caused by Optifine, but I thought it couldn't hurt to post it here.

The issue is, a member of my server crashes when he gets near Spruce Shelves. It doesn't happen without Optifine. Here's the crashlog: https://pastebin.com/aCRMwhDT

**Comment by DreadBoy** [comment]
It also happens with Fancy Signs, I just stumbled upon it. Crash log if needed:

https://paste.ee/p/7o7ZT

**Comment by Nuchaz** [comment]
I have a fix in place for this which will be in the next update (coming soon)
