### ISSUE TITLE
Shelves rotating on their own (BiblioCraft 2.2.1 for MC1.10.2)

### ISSUE THREAD

**Issue by UnixRonin** [Nuchaz/BiblioCraft#446]
I'm experiencing an issue on 1.10.2 with both regular shelves and bookshelves in which after a restart of the server, they will be facing east, regardless of the orientation in which they were placed.  The contents are still there on the shelves, but are invisible.  If one of several adjacent shelves is broken, it MAY cause the other adjacent shelves to snap back to the correct orientation, and the shelf contents reappear.

**Comment by Nuchaz** [comment]
I believe this to be related to #418 and am going to close this to consolidate. I think I have a good idea what is casuing this and am working on a fix now.
