### ISSUE TITLE
Dyes produce wrong color sword pedestal (Bibliocraft v2.2.1/Minecraft 1.10.2)

### ISSUE THREAD

**Issue by LordRael** [Nuchaz/BiblioCraft#447]
None of the dyes produce the corresponding color of sword pedestal.  Examples:  Green dye produces a magenta pedestal, light gray dye produces a green pedestal, yellow dye produces a red pedestal.  Please see attached image.

![2017-05-06_00 09 30](https://cloud.githubusercontent.com/assets/28473514/25770036/4cac183e-31f0-11e7-8e80-9edece4b4a01.png)

**Comment by Nuchaz** [comment]
This will be fixed in the next release.

**Comment by gryttr** [comment]
I'm still seeing this in Bibliocraft 2.3.1 for Minecraft 1.11.2. The dyes produce the correct colors, but wool still produces the incorrect colors.
