### ISSUE TITLE
Chases can be enchanted by anvil

### ISSUE THREAD

**Issue by purpleposeidon** [Nuchaz/BiblioCraft#449]
1. Make a cheap chase by copying eg a bane of arthropods book, costing like 2 xp or something.
2. Add mending to the chase using the anvil.
3. Use the chase to get 3 copies of the expensive book for basically nothing instead of 40 levels.

**Comment by Nuchaz** [comment]
Thanks for the report, I wasn't aware that could be done. I bet this goes back several versions too. I'll try to get a fix in for the next release I am currently working. I am planning to do a bugfix release for versions for both MC 1.7.10 and 1.10.2.

**Comment by Nuchaz** [comment]
A fix for this will be in the next version(s), coming soon.
