### ISSUE TITLE
Tables do not connect

### ISSUE THREAD

**Issue by schismatix** [Nuchaz/BiblioCraft#450]
1.11.2 v2.3.0
The table does not connect properly when more than 1 are placed together. The original remains a single table model and the remaining do not connect to either the first table placed or any subsequent ones.

**Comment by Nuchaz** [comment]
Ah, I see. I guess I forgot to test that one. It seems to be working on the 1.10.2 version, but not 1.11, so something must have changed. I'll be sure to get a fix in for this on the next update.

**Comment by Nuchaz** [comment]
Fixed in v2.3.1. Should have updated and closed this at the time, but yeah, fixed now.
