### ISSUE TITLE
[1.11.2] Bookshelf Crash

### ISSUE THREAD

**Issue by EmosewaGamer** [Nuchaz/BiblioCraft#451]
On the first 1.11.2 version it seems that after placing down a bookshelf, when connecting to the world/server, at random, the client crashes: https://pastebin.com/LJ9hUqkZ By the looks of it it has to do with the rendering of the model.

**Comment by Nuchaz** [comment]
I haven't been able to reproduce this yet, but I will mess around some more and see what I can figure out. I had put in a number of changes and checks to try to stop any kind of crash like this, so I am not sure why this is happening. If I can get it to reproduce I'll be able to test things better. I

**Comment by Nuchaz** [comment]
I have a fix out for this. I rolled the fix into BiblioCraft v2.1.4 for MC 1.9.4, BiblioCraft v2.2.4 for MC 1.10.2 and BiblioCraft v2.3.2 for MC 1.11.2. Closing the issue. You should be able to load worlds that have been permanently crashed by this bug.  Let me know if you experience anything weird.
