### ISSUE TITLE
[2.2.2] Bibliocraft/Better Foliage Crash

### ISSUE THREAD

**Issue by Alaberti** [Nuchaz/BiblioCraft#453]
https://pastebin.com/Sc3Pak71

I see better foliage in the trace, I know it does something with logs to make them look rounded but I'm not sure if that's even relevant.

**Comment by Nuchaz** [comment]
I see optifine installed and I suspect it may be related to that. Another report, #451 seems related.
I haven't gotten this to duplicate yet with my setup with optifine, but I am trying to figure it out.

**Comment by Nuchaz** [comment]
I have a fix out for this. I rolled the fix into BiblioCraft v2.1.4 for MC 1.9.4, BiblioCraft v2.2.4 for MC 1.10.2 and BiblioCraft v2.3.2 for MC 1.11.2. Closing the issue. You should be able to load worlds that have been permanently crashed by this bug.  Let me know if you experience anything weird.
