### ISSUE TITLE
IMC for shelves and tool racks

### ISSUE THREAD

**Issue by ivan-petrovic-soprex** [Nuchaz/BiblioCraft#454]
I have a book in my mod, but, as far as i know, no way to register it with bibliocraft shelves (i won't be so rude as to poke other mods config files, even though i could).

Is there already a system i don't know about? If you want an example code for IMC message processing, let me know.

thanks

**Comment by Nuchaz** [comment]
Currently, no IMC stuff or anything. I was meaning to implement that at some point, just haven't gotten around to it. All I am doing right now is searching a list of strings and compare against the display name and the unlocalized name of the itemstack.

Whats the unlocalized name of your book?, I'll add to my internal list.

**Comment by ivan-petrovic-soprex** [comment]
getUnlocalizedName will return "item.herbarium". proper name (for "give" command, for example) is "moonlightherbarium:herbarium". 

can't say i feel good about this - ok, you'll handle my immediate issue (thanks, btw), but then other people need to pull your sleeve...

**Comment by Nuchaz** [comment]
ok, my next update will include support for your book. I'll add support for the IMC stuff at some point. I don't mind doing it this way for now. There is config support so no matter what the end users are free to add whatever items to the list so it works with the bookcase or whatever.
