### ISSUE TITLE
[1.11.2] Custom Painting, Only allowed lowercase name [Bug]?

### ISSUE THREAD

**Issue by BearlyCompetent** [Nuchaz/BiblioCraft#457]
Custom Paintings are only working if the file names are all lower case, never used to matter. Intentional change or bug?

If they have an uppercase name, Biblocraft notices the files, but they do not render in the printing press. Missing Pink/black texture appears instead.

**Comment by Nuchaz** [comment]
This is unintended intended. In other words, it is intended, but it wasn't my personal intention. That is related to a change in vanilla minecraft, everything has to be lowercase now. Texture names, .lang files, translations, enums in my code, mod names, etc. So now minecraft just will straight up ignore any file name (like textures) that have capital letters in them. I don't know why they did they or what benefit this has, but it has been a pain in the butt, I know that. So I think we can blame Mojang for this one.

**Comment by BearlyCompetent** [comment]
Thanks for the quick response, love the mod btw so happy to see it in 1.11.2!
