### ISSUE TITLE
Atlas causes me to have internal server error

### ISSUE THREAD

**Issue by Konclan** [Nuchaz/BiblioCraft#458]
https://pastebin.com/2hZzdxf9
As soon as I crafted it I can no longer log back into my server

**Comment by Nuchaz** [comment]
Thanks for the report, I was able to easily duplicate this. I will try to get this fixed asap. I guess I had forgot to test the atlas on a server.

**Comment by Konclan** [comment]
Awesome to see a developer reply so fast, hope there is an update soon 👍

**Comment by Nuchaz** [comment]
I got it figured out. I am setting a unique ID for each atlas and I was using the system time with a little math to do so. I was checking the system time on the client, which doesn't exist on the server. That was my bad. I am checking it from the server now and it seems to be working. Your world you crafted the atlas in should load as well with no problems after the update. 

If all goes well, I plan to try to get an update out later today / this evening. I had some other bugs I was working on I wanted to get a fix for out.

**Comment by Nuchaz** [comment]
I just released an update with a fix for this in it. The problem existed in versions for minecraft 1.9.4, 1.10.2, and 1.11.2, so I released an update for all 3.
