### ISSUE TITLE
Bibliowoods Forestry is looking for creative tab on dedicated server and thus crashes

### ISSUE THREAD

**Issue by ScottKillen** [Nuchaz/BiblioCraft#459]
I have attached partial log.

[log.txt](https://github.com/Nuchaz/BiblioCraft/files/1035908/log.txt)

**Comment by Nuchaz** [comment]
Are you using BiblioCraft v2.3.1?, It is the only version that supports the new BiblioWoods. The class file the error is showing doesn't exist in BiblioCraft v2.3.0, only v2.3.1.

**Comment by ScottKillen** [comment]
Sorry, @Nuchaz .

I didn't pick up on the fact that Bibliocraft had updated, nor did my server complain that BiblioWoods had a hard dependency on a version beyond 2.3.0.

Thanks.

**Comment by Nuchaz** [comment]
No worries. I should have set the bibliowoods with a hard dependency for BiblioCraft v2.3.1, that would have been smart, but I didn't think of doing that.

**Comment by ScottKillen** [comment]
No one can be brilliant 100% of the time--however, your brilliancy rate far surpasses mine. 😀
