### ISSUE TITLE
Tesselating Block Crash (oak seat)

### ISSUE THREAD

**Issue by Avarice** [Nuchaz/BiblioCraft#461]
https://paste.ee/p/PeGl3
Disabled Optifine, still crashed, going to try updating to 2.3.1
Updated to 2.3.1 Still crashing

**Comment by IchigoGames** [comment]
i think this might be the same crash i am getting https://pastebin.com/fT8ixkCj

**Comment by Nuchaz** [comment]
I am still trying to figure this one out. I haven't been able to reproduce it on my computer yet so it has been quite difficult to figure out and fix.

**Comment by IchigoGames** [comment]
sorry forgot to report back that the crash i had was from a issue with the world save after loading a backup of the world everything was fine.

**Comment by Nuchaz** [comment]
I have a fix out for this. I rolled the fix into BiblioCraft v2.1.4 for MC 1.9.4, BiblioCraft v2.2.4 for MC 1.10.2 and BiblioCraft v2.3.2 for MC 1.11.2. Closing the issue. You should be able to load worlds that have been permanently crashed by this bug.  Let me know if you experience anything weird.

**Comment by Avarice** [comment]
Thank you so much ♥ Let you know how it goes.
