### ISSUE TITLE
Custom paintings showing up blank?

### ISSUE THREAD

**Issue by KianaAnyce** [Nuchaz/BiblioCraft#462]
I recently installed this mod for 1.11 and tried out the custom painting feature using the painting press. To test it out, I downloaded the example resource pack template that's on the BiblioCraft website and put in a sample picture to use in my game. It worked great! I now wanted to create more custom paintings to use so I unzipped the zip resource pack I had in my game and added the new ones in. I then zipped the file back up and put it back in the game's resource pack folder. However, for some reason the new paintings I added today aren't showing up correctly:
![exampleissue](https://cloud.githubusercontent.com/assets/29132510/26703000/20e8e80a-46ed-11e7-9ec8-afc6808ded69.png)
Only the original picture I added when I initially installed the mod is showing up. The new paintings I made are made the same exact way I made the first one, and they're in png format, so I'm a bit confused why this is happening. I even tried re-creating a new resource pack with the custom paintings multiple times, but it still has the same result every time? 

Here's the pictures that I've been trying to use: 
(the very last picture was the 1st one I ever made and it's the only one that's working)
![exampleissue2](https://cloud.githubusercontent.com/assets/29132510/26703084/92a4fbdc-46ed-11e7-805f-60b2601a84eb.png)

I could just maybe be doing something wrong, but I appreciate any help!
Thank you! (:

**Comment by helmutfork** [comment]
Could the capitalization on the new files be the problem?  It seems the file name for the only one that is working is in all lowercase.

**Comment by KianaAnyce** [comment]
hmm that's interesting...I'll try it out and let you know!

**Comment by KianaAnyce** [comment]
It worked! Thank you so much!
