### ISSUE TITLE
Missing mcmod.info

### ISSUE THREAD

**Issue by The-Fireplace** [Nuchaz/BiblioCraft#464]
![2017-06-04_00 29 11](https://cloud.githubusercontent.com/assets/5914284/26759188/d67e9fcc-48bc-11e7-88da-ae3d8d83b9c5.png)
Bibliocraft 2.3.1, Minecraft 1.11.2

**Comment by Nuchaz** [comment]
Thanks for the report. I think is what happened is the mcmod.info is targted for the modid "BiblioCraft" where in 1.11.2 I was forced to lowercase the modid to "bibliocraft". I'll have this fixed in the next release.

**Comment by Nuchaz** [comment]
I fixed this in the latest version I just release. BiblioCraft v2.3.2.
