### ISSUE TITLE
Map Frames?

### ISSUE THREAD

**Issue by Placid-Storm** [Nuchaz/BiblioCraft#479]
Was it intentional to make the Map Frames require 8 slabs and one stick? The wiki is opposite, that's why I ask. I was reading your json recipe files.

**Comment by Placid-Storm** [comment]
I edited all the Map Frames to match the wiki. All the recipes work here too. I just saved the json file as a txt.

[oak_mapframe.txt](https://github.com/Nuchaz/BiblioCraft/files/1128908/oak_mapframe.txt)
[jungle_mapframe.txt](https://github.com/Nuchaz/BiblioCraft/files/1128906/jungle_mapframe.txt)
[framed_mapframe.txt](https://github.com/Nuchaz/BiblioCraft/files/1128909/framed_mapframe.txt)
[darkoak_mapframe.txt](https://github.com/Nuchaz/BiblioCraft/files/1128907/darkoak_mapframe.txt)
[birch_mapframe.txt](https://github.com/Nuchaz/BiblioCraft/files/1128910/birch_mapframe.txt)
[acacia_mapframe.txt](https://github.com/Nuchaz/BiblioCraft/files/1128905/acacia_mapframe.txt)
[spruce_mapframe.txt](https://github.com/Nuchaz/BiblioCraft/files/1128911/spruce_mapframe.txt)

**Comment by Nuchaz** [comment]
Thanks for the report. Another derp on my part it seems. I guess I was bound to make a couple mistakes redoing like 400 recipes. I'll make sure the fix is in place for next release

**Comment by Nuchaz** [comment]
Just released an update with a fix for this.
