### ISSUE TITLE
[1.10.2-1.11.2] Item size bug

### ISSUE THREAD

**Issue by Kundello** [Nuchaz/BiblioCraft#483]
Can you please fix size of big writing book, print press plates, atlas, lock and key, and other items and its position in hand? They are giant comparing to normаl books or items.
For example:
Normal book item render: http://imgur.com/XKaT9sf
Big book item render: http://imgur.com/pgToLdp
Find this bug on 1.10 and 1.11 builds

**Comment by Nuchaz** [comment]
I'll look into it. With simple 2D items in the past I never had to worry about scaling and stuff since vanilla took care of it. I guess that must be another thing now that needs to be done.

**Comment by Nuchaz** [comment]
This will be fixed in the next release, all I needed to do was change "builtin/generated" to "item/generated" in the .json files for the different models.

**Comment by Kundello** [comment]
Thank you!
