### ISSUE TITLE
[1.12][2.4.3] Crash with CodeChickenLib

### ISSUE THREAD

**Issue by Kris1432** [Nuchaz/BiblioCraft#490]
Forge: 2424
Version: 2.4.3

Cause: Teleported back to my house where clipboards were.

Update: Another user on my server has now had the same crash just loading my base up.

Pastebin: https://pastebin.com/tbVyuiNe

**Comment by Nuchaz** [comment]
I was hoping I had that fixed, guess there is still something there. I'll investigate this. Thanks for the crash report.

**Comment by Kris1432** [comment]
any news on this, I can't play my game properly as i'm crashing a lot.

**Comment by Cobra1117** [comment]
I've already had to restore from backup once--it would be really nice to get this one fixed!

**Comment by thisischrys** [comment]
Also just had this issue

**Comment by Xules01** [comment]
I'm having this issue as well.  When I get to close to the clipboard it crashes the game.  Posted on Oneprobe and Bibliocraft.

[crash-2018-05-03_19.36.25-client.txt](https://github.com/McJty/TheOneProbe/files/1973060/crash-2018-05-03_19.36.25-client.txt)

**Comment by Nuchaz** [comment]
I think I figured out a fix for this. Expect a fix in the next release, which will be v2.4.4 for MC 1.12.2. I am closing this issue for now. Let me know if anyone still has issues after the next release.
