### ISSUE TITLE
[1.12] [2.4.3] Disc Rack recipe issue

### ISSUE THREAD

**Issue by Riffmaker2704** [Nuchaz/BiblioCraft#491]
Hey guys, I noticed that the recipe is broken. I tried different sorts of slabs, different workbenches and placed the sticks in the upper 3 squares, as well as those in the middle. 
Actually I have no experiences with json files. I weren't even able to find the recipes in the .jar file.

Anyway, great work with that mod! I like it really much. :)

**Comment by Nuchaz** [comment]
I'll get this fixed. I've had a few mistakes here and there with the recipes since they all had to be redone for minecraft 1.12.

**Comment by Nuchaz** [comment]
The recipe was using the bibliocraft boards instead of slabs. I'll have a fix in the next release, v2.4.4 for MC 1.12.2
