### ISSUE TITLE
[1.10.2] [1.12.2??] Clocks don't emit redstone singnal on correct time

### ISSUE THREAD

**Issue by Sanofus** [Nuchaz/BiblioCraft#501]
It seems that the clocks dont give a signal if its turned on. They just give a singal twice if a marks are red. But I think that is not the intented behaivor.

**Comment by JonasCiss** [comment]
I will chek if this is present in the current version. If not this issue will be closed.

**Comment by Sanofus** [comment]
closing for new issue.
