### ISSUE TITLE
Marker pole and clipboard lack a crafting recipe, a proper texture, and localization

### ISSUE THREAD

**Issue by ghost** [Nuchaz/BiblioCraft#525]
**Minecraft version**: 1.10.2
**BiblioCraft version**: 2.2.5

**Comment by Nuchaz** [comment]
These two blocks are blocks that shouldn't be crafted, but judging by some of the other reports, this seems to have caused some issues in not having the recipe json and stuff for these blocks. I will have a fix for this in the next release.
