### ISSUE TITLE
Server thread/FATAL Error executing task 1.12

### ISSUE THREAD

**Issue by unstablecraft** [Nuchaz/BiblioCraft#533]
https://github.com/SpongePowered/SpongeForge/issues/1948

i made this issue earlier this week  @spongeforge  but the fatel error is your part of the deal :D

**Comment by Nuchaz** [comment]
I am working on an update and I think I have a fix in place for this. It looks like there was some unanticipated interaction between my mod and sponge. I want to do some more testing, but look for a fix in upcoming version 2.4.4
