### ISSUE TITLE
Tesselation Error Crashing Client - Clipboard

### ISSUE THREAD

**Issue by xBlizzDevious** [Nuchaz/BiblioCraft#542]
I'm playing All The Mods 3 and have had a couple of client crashes since I placed my clipboard on the wall with sneak+right click.

It's happened a couple of times when breaking several ores at once nearby and just now while taking some stuff out of an Applied Energistics system.

Here's a crash report:
https://pastebin.com/7wWn6kq2

Please ask for any extra details required.

**Comment by dannydjdk** [comment]
Appears to be a duplicate of #540

**Comment by Nuchaz** [comment]
I think I figured out a fix for this. Expect a fix in the next release, which will be v2.4.4 for MC 1.12.2. I am closing this issue for now. Let me know if anyone still has issues after the next release.
