### ISSUE TITLE
Rendering issues on forge 2624

### ISSUE THREAD

**Issue by Sunconure11** [Nuchaz/BiblioCraft#543]
![screenshot 2018-03-04 18 29 09](https://user-images.githubusercontent.com/5614902/36952153-0aba7ad2-1fda-11e8-8dfd-eb19f72d0e3f.png)
![screenshot 2018-03-04 18 30 10](https://user-images.githubusercontent.com/5614902/36952159-164384f2-1fda-11e8-8744-2e7ef72d9a74.png)

Note: I am using texfix.

Version of forge installed: 14.23.2.2624

**Comment by Nuchaz** [comment]
I think this may have been fixed with a newer version of forge. I can't seem to reproduce with newer forge.
