### ISSUE TITLE
Clipboard renders sideways in TC Item Rack and Bibliocraft shelves

### ISSUE THREAD

**Issue by Lethann** [Nuchaz/BiblioCraft#546]
Minecraft 1.12.2
Peace of Mind modpack 1.8.1

Bibliocraft 2.4.3
TC 2.9.0.55

Pretty self explanatory:

![2018-03-09_12 21 17](https://user-images.githubusercontent.com/25929754/37223003-b49b75c0-2394-11e8-82a5-1919a207c371.png)

![2018-03-09_12 27 08](https://user-images.githubusercontent.com/25929754/37223171-45ce90ea-2395-11e8-8eee-4b1bfd8fa3f6.png)

**Comment by Nuchaz** [comment]
This will be fixed in the next release which will be v2.4.4 for MC 1.12.2. I plan to do a release soon within the next few days/week.
