### ISSUE TITLE
[1.12] java.lang.NullPointerException: Rendering ingredient

### ISSUE THREAD

**Issue by mdatoo** [Nuchaz/BiblioCraft#552]
Seems to crash when I search for the letter J in the search box in JEI. I have tested it with a few other letters and it seems to be fine (seems to be an issue with the rendering of an item).

This occurs on survival mode with cheats on 1.12.2.

[crash-2018-03-20_19.30.42-client.txt](https://github.com/Nuchaz/BiblioCraft/files/1830914/crash-2018-03-20_19.30.42-client.txt)

**Comment by dannydjdk** [comment]
We are experiencing a similar intermittent client side crash when a clipboard is placed in the world. Some players will crash when in the vicinity of the placed clipboard. We are using foamfix, but the OP was not, so it's not likely to be a contributing factor.

BiblioCraft 2.4.3
Forge 14.23.2.2611
Minecraft 1.12.2
Pack https://minecraft.curseforge.com/projects/integrated-progressions

https://pastebin.com/YsH7Xa1U

**Comment by Nuchaz** [comment]
It looks like an interaction between JEI and my mod and JEI trying to render the clipboard. I'll do some investigating and see if I can figure out a fix for this.

**Comment by Nuchaz** [comment]
I think it is crashing when it looks for the .json recipe file and finds nothing. So I created a json recipe for it with just a black list of ingredients. Hopefully that will fix this crash. Look for a fix in the upcoming version 2.4.4.
