### ISSUE TITLE
Textures error!

### ISSUE THREAD

**Issue by FabioZumbi12** [Nuchaz/BiblioCraft#555]
I having an issue… the print will say for me:

https://prnt.sc/ivysc7
https://prnt.sc/ivysrz

Forge version: forge-1.12.2-14.23.2.2633-universal
MOD version: BiblioCraft[v2.4.3][MC1.12.0]
SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2970

**Comment by Nuchaz** [comment]
I think this may have been fixed with a newer version of forge. I can't seem to reproduce with newer forge.
