### ISSUE TITLE
NPE occurred in class BiblioModelColor causing client crash

### ISSUE THREAD

**Issue by momocow** [Nuchaz/BiblioCraft#563]
As the [crash report](https://pastebin.com/ER60Y3iW) here.

I'm not really sure how to reproduce the crash, my client crashed in sudden when I was walking around at home in the overworld. (No GUI opening)

I'm playing with modpack, SevTech v3.0.6, and Bibliocraft v2.4.3.

Thanks.

**Comment by Nuchaz** [comment]
I think I found a fix for this and have it in place. Expect it in the next version, which will be v2.4.4 for Minecraft v1.12.2. I plan to get it out real soon.
