### ISSUE TITLE
[1.12.2] Crash when standing on block measuring tape is used on.

### ISSUE THREAD

**Issue by GrucciNishikino** [Nuchaz/BiblioCraft#576]
So [this](https://pastebin.com/Qist7HcK) crash occurred when I used the measuring tape on the block I was standing on. The game, unlike previous crashes I have dealt with for other reasons, immediately closed and ended the java process, which is likely unrelated. Thank you in advance for any help.

**Comment by Nuchaz** [comment]
Thanks for the crash report. I have an idea on how I might be able to fix this. I will implement for the next release.

**Comment by Nuchaz** [comment]
I just released v2.4.5 of BiblioCraft which I believe has a fix for this. Feel free to reopen this issue with a fresh crash log if this happens again.
