### ISSUE TITLE
Crash from Tape Measure

### ISSUE THREAD

**Issue by ResqDiver1317** [Nuchaz/BiblioCraft#580]
We just launched a custom 1.12.2 modpack for our community and anytime someone uses the tape measure, it kicks them out of the game and give a couple different messages. I've done it 3 times in a row. Twice I got the message about a fatal error and the last time I had a message saying Internal Exception: java.io.IOException. It's not crashing me all the way back to Technic so it's not giving me a crash report but here is my log and debug files in case they are of any help (I had to zip the debug file as it was too big to upload normally. I saw someone else with an issue reported related to standing on the block, but that is not the case here as I have made it a point to not stand on the block. 
[latest - Copy.log](https://github.com/Nuchaz/BiblioCraft/files/2087569/latest.-.Copy.log)
[debug - Copy.zip](https://github.com/Nuchaz/BiblioCraft/files/2087570/debug.-.Copy.zip)

**Comment by kriogenic** [comment]
Hi, just wanted to note a few users of our mod pack A Bit More of Everything (1.10.2) are experiencing a similar crash with the tape measure. One of the users noted this "Thats the issue right there. It keeps the original measuring mark there and if you use it again it will crash everything". He also posted this image
![image](https://user-images.githubusercontent.com/389938/41339181-8fdad322-6f37-11e8-9a38-7607738460fd.png)

It would be really nice if this could be fixed as a majority of our users love this mod and it would be sad to have to remove the recipe for the tape.

**Comment by Rsslone** [comment]
I also have an issue with the tape measure, however it only kicks out to main menu. There is no error in the latest.log or debug.log.

The last line before the client times out is
"[main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] Measurement North/South = 7"
The rest of the log is just logs for rejoining the server.

**Comment by Nuchaz** [comment]
I think I may have a fix for this in place but I am not exactly sure. I'll have it in the next release which I expect to put out within the next few days. Let me know after that if the issue persists. 

The update will be for 1.12.2 for now, I would like to backport some of these fixes to a couple of the popular versions before calling it quits on those versions, but I can't say when I will get that done. Probably before a version for 1.13 is ready since I would like to kind of close the book on versions of MC before 1.12.2.

**Comment by Nuchaz** [comment]
A am pretty sure I have a fix in place for v2.4.5. If this occurs again, feel free to reopen this issue and I will continue to investigate.

**Comment by ResqDiver1317** [comment]
We updated a few days ago and I tested the tape measure again tonight and we are still crashing when using it just like before.

**Comment by Nuchaz** [comment]
@ResqDiver1317 Could you post a copy of a crash log from the recent tape measure crash?
I think I've found another crash that I can fix, but I'm not sure if its the same issue you are having.

**Comment by ResqDiver1317** [comment]
I'm leaving work now, when I get home, I'll crash myself with it again and send the logs.

**Comment by Tencao** [comment]
Can confirm users on my server are also crashing from this on the latest version
