### ISSUE TITLE
[1.12.2] Suggestion - Make Mystcraft's Symbol Portfolios shelvable

### ISSUE THREAD

**Issue by Geethebluesky** [Nuchaz/BiblioCraft#582]
Information in here: https://github.com/XCompWiz/Mystcraft-Issues/issues/256

Thanks!

**Comment by Nuchaz** [comment]
I'll be sure to add support for the next update. I actually wasn't aware Mystcraft was updated for 1.12.2, that's great news. I always loved that mod.

**Comment by Nuchaz** [comment]
I just released v2.4.5 of BiblioCraft which now supports the Mystcraft stuff on bookcases.
