### ISSUE TITLE
"On The Dynamics of Integration" cannot be placed in a Oak Bookcase

### ISSUE THREAD

**Issue by ghost** [Nuchaz/BiblioCraft#597]
Crosslinking from bug posted on Integrated Dynamics site, Bibliocraft Issue per that dev.

https://github.com/CyclopsMC/IntegratedDynamics/issues/604

**Comment by QuantumStatement** [comment]
You should add unlocalized name of this book (`on_the_dynamics_of_integration`) in `AllowedBooks` config entry in Bibliocraft config file
`S:AllowedBooks=book, map, journal, plan, thaumonomicon, necronomicon, lexicon, print, notes, spell, library, tome, encyclopedia, on_the_dynamics_of_integration`
![2018-07-18_13 34 18](https://user-images.githubusercontent.com/35406698/42876637-f67befb2-8a8f-11e8-9977-6af0b4063075.png)

**Comment by Nuchaz** [comment]
I'll go ahead and add this to the default settings too so it will automatically work in the next update.
