### ISSUE TITLE
Missing Block Textures

### ISSUE THREAD

**Issue by AgentCPU0** [Nuchaz/BiblioCraft#727]
First, this has been reported before, let me get that out of the way. But it was never patched, so I'm reporting it anyway

Textures on BiblioCraft blocks will sometimes break. One of two things can happen. First, the blocks will render important things, such as text or items on display, with the decoration portion, for example planks or stone, rendering as a ghost block one block away. This happens more often with framed blocks decorated with a furniture paneler. Second, which happens way more often, the blocks just render as full, untextured pink and black blocks, regardless of the original block's hitbox

I have found a workaround, but it's not always successful. By closing both the game and the launcher, this can be reset and fixed. It's not a perfect solution, it would be better if it was patched, but it's what I found for now

As I said, this has been previously reported. But all of the posts regarding it are now closed, and it's still broken. Please look into it, it's annoying to deal with

**Comment by Ravin890** [comment]
The mod has not updated in over 2 years, so I am not sure if Nuchaz is still working on this.

**Comment by AgentCPU0** [comment]
Is it open source? Because maybe someone else can fix it

**Comment by Ravin890** [comment]
Not that I am aware of

**Comment by AgentCPU0** [comment]
That's it. Fuck this mod. If the dev is too lazy to either fix this or allow others to fix it for them, then they should just delete the project completely
